---
name: str()
path: str()
augment_path: str(required=False)
no_delete: bool(required=False)
no_delete_attributes: bool(required=False)
default_delete_attributes: bool(required=False)
test_tags: list(str(), required=False)
skip_minimum_test: bool(required=False)
no_augment_config: bool(required=False)
ds_description: str(required=False)
res_description: str(required=False)
doc_category: str()
attributes: list(include('attribute'), required=False)
test_prerequisites: list(include('test_prerequisite'), required=False)
---
attribute:
  yang_name: str()
  yang_scope: str(required=False)
  tf_name: str(required=False)
  xpath: str(required=False)
  type: enum('String', 'Int64', 'Bool', 'List', 'StringList', 'Int64List', required=False)
  type_yang_bool: enum('empty', 'presence', 'boolean', required=False)
  id: bool(required=False)
  reference: bool(required=False)
  mandatory: bool(required=False)
  optional: bool(required=False)
  write_only: bool(required=False)
  exclude_test: bool(required=False)
  exclude_example: bool(required=False)
  description: str(required=False)
  example: any(str(), int(), bool(), required=False)
  enum_values: list(str(), required=False)
  min_int: int(required=False)
  max_int: int(required=False)
  string_patterns: list(str(),required=False)
  string_min_length: int(required=False)
  string_max_length: int(required=False)
  default_value: any(str(), int(), bool(), required=False)
  requires_replace: bool(required=False)
  no_augment_config: bool(required=False)
  delete_parent: bool(required=False)
  no_delete: bool(required=False)
  test_tags: list(str(), required=False)
  attributes: list(include('attribute'), required=False)

test_prerequisite:
  path: str()
  no_delete: bool(required=False)
  attributes: list(include('test_attribute'), required=False)
  lists: list(include('test_list'), required=False)
  dependencies: list(int(), required=False)

test_attribute:
  name: str()
  value: any(str(), int(), bool())
  reference: str(required=False)

test_list:
  name: str()
  key: str()
  items: list(include('test_list_item'))

test_list_item:
  attributes: list(include('test_attribute'), required=False)
