// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource

func TestAccDataSourceIosxeMonitorSession(t *testing.T) {
	if os.Getenv("C9000V") == "" {
		t.Skip("skipping test, set environment variable C9000V")
	}
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_monitor_session.test", "destination_interface.0.name", "HundredGigE1/0/1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_monitor_session.test", "destination_interface.0.encapsulation", "replicate"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_monitor_session.test", "source_interface.0.name", "HundredGigE1/0/2"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_monitor_session.test", "source_interface.0.direction", "both"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxeMonitorSessionConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig

func testAccDataSourceIosxeMonitorSessionConfig() string {
	config := `resource "iosxe_monitor_session" "test" {` + "\n"
	config += `	session_id = 1` + "\n"
	config += `	destination_interface = [{` + "\n"
	config += `		name = "HundredGigE1/0/1"` + "\n"
	config += `		encapsulation = "replicate"` + "\n"
	config += `	}]` + "\n"
	config += `	source_interface = [{` + "\n"
	config += `		name = "HundredGigE1/0/2"` + "\n"
	config += `		direction = "both"` + "\n"
	config += `	}]` + "\n"
	config += `}` + "\n"

	config += `
		data "iosxe_monitor_session" "test" {
			session_id = 1
			depends_on = [iosxe_monitor_session.test]
		}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
