// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSource

func TestAccDataSourceIosxeDHCPPool(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dhcp_pool.test", "domain_name", "example.com"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dhcp_pool.test", "bootfile", "boot.cfg"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dhcp_pool.test", "network_number", "10.1.1.0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dhcp_pool.test", "network_mask", "255.255.255.0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dhcp_pool.test", "default_routers.0", "10.1.1.1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dhcp_pool.test", "dns_servers.0", "10.1.1.1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dhcp_pool.test", "lease_days", "1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dhcp_pool.test", "lease_hours", "12"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dhcp_pool.test", "lease_minutes", "30"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dhcp_pool.test", "options.0.option_code", "150"))
	checks = append(checks, resource.TestCheckResourceAttr("data.iosxe_dhcp_pool.test", "options.0.ascii", "10.1.1.1"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIosxeDHCPPoolPrerequisitesConfig + testAccDataSourceIosxeDHCPPoolConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAccDataSource

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
const testAccDataSourceIosxeDHCPPoolPrerequisitesConfig = `
resource "iosxe_yang" "PreReq0" {
	path = "/Cisco-IOS-XE-native:native/vrf/definition[name=VRF1]"
	delete = false
	attributes = {
		"name" = "VRF1"
		"address-family/ipv4" = ""
	}
}

`

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccDataSourceConfig

func testAccDataSourceIosxeDHCPPoolConfig() string {
	config := `resource "iosxe_dhcp_pool" "test" {` + "\n"
	config += `	delete_mode = "attributes"` + "\n"
	config += `	name = "POOL1"` + "\n"
	config += `	domain_name = "example.com"` + "\n"
	config += `	bootfile = "boot.cfg"` + "\n"
	config += `	network_number = "10.1.1.0"` + "\n"
	config += `	network_mask = "255.255.255.0"` + "\n"
	config += `	default_routers = ["10.1.1.1"]` + "\n"
	config += `	dns_servers = ["10.1.1.1"]` + "\n"
	config += `	lease_days = 1` + "\n"
	config += `	lease_hours = 12` + "\n"
	config += `	lease_minutes = 30` + "\n"
	config += `	options = [{` + "\n"
	config += `		option_code = 150` + "\n"
	config += `		ascii = "10.1.1.1"` + "\n"
	config += `	}]` + "\n"
	config += `	depends_on = [iosxe_yang.PreReq0, ]` + "\n"
	config += `}` + "\n"

	config += `
		data "iosxe_dhcp_pool" "test" {
			name = "POOL1"
			depends_on = [iosxe_dhcp_pool.test]
		}
	`
	return config
}

// End of section. //template:end testAccDataSourceConfig
