// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type Banner struct {
	Device              types.String `tfsdk:"device"`
	Id                  types.String `tfsdk:"id"`
	DeleteMode          types.String `tfsdk:"delete_mode"`
	ExecBanner          types.String `tfsdk:"exec_banner"`
	LoginBanner         types.String `tfsdk:"login_banner"`
	PromptTimeoutBanner types.String `tfsdk:"prompt_timeout_banner"`
	MotdBanner          types.String `tfsdk:"motd_banner"`
}

type BannerData struct {
	Device              types.String `tfsdk:"device"`
	Id                  types.String `tfsdk:"id"`
	ExecBanner          types.String `tfsdk:"exec_banner"`
	LoginBanner         types.String `tfsdk:"login_banner"`
	PromptTimeoutBanner types.String `tfsdk:"prompt_timeout_banner"`
	MotdBanner          types.String `tfsdk:"motd_banner"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data Banner) getPath() string {
	return "Cisco-IOS-XE-native:native/banner"
}

func (data BannerData) getPath() string {
	return "Cisco-IOS-XE-native:native/banner"
}

// getXPath returns the XPath for NETCONF operations
func (data Banner) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/banner"
	return path
}

func (data BannerData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/banner"
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data Banner) toBodyXML(ctx context.Context, config Banner) string {
	body := netconf.Body{}
	if !data.ExecBanner.IsNull() && !data.ExecBanner.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/exec/banner", data.ExecBanner.ValueString())
	}
	if !data.LoginBanner.IsNull() && !data.LoginBanner.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/login/banner", data.LoginBanner.ValueString())
	}
	if !data.PromptTimeoutBanner.IsNull() && !data.PromptTimeoutBanner.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/prompt-timeout/banner", data.PromptTimeoutBanner.ValueString())
	}
	if !data.MotdBanner.IsNull() && !data.MotdBanner.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/motd/banner", data.MotdBanner.ValueString())
	}
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// End of section. //template:end toBodyXML

// Section below is manually maintained to apply TrimNetconfTrailingWhitespace for banner attributes.
// This prevents Terraform drift caused by trailing whitespace in NETCONF responses.
// See: https://github.com/CiscoDevNet/terraform-provider-iosxe/issues/686

func (data *Banner) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/exec/banner"); value.Exists() && !data.ExecBanner.IsNull() {
		data.ExecBanner = types.StringValue(helpers.TrimNetconfTrailingWhitespace(value.String()))
	} else {
		data.ExecBanner = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/login/banner"); value.Exists() && !data.LoginBanner.IsNull() {
		data.LoginBanner = types.StringValue(helpers.TrimNetconfTrailingWhitespace(value.String()))
	} else {
		data.LoginBanner = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/prompt-timeout/banner"); value.Exists() && !data.PromptTimeoutBanner.IsNull() {
		data.PromptTimeoutBanner = types.StringValue(helpers.TrimNetconfTrailingWhitespace(value.String()))
	} else {
		data.PromptTimeoutBanner = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/motd/banner"); value.Exists() && !data.MotdBanner.IsNull() {
		data.MotdBanner = types.StringValue(helpers.TrimNetconfTrailingWhitespace(value.String()))
	} else {
		data.MotdBanner = types.StringNull()
	}
}

// End of manually maintained section.

// Section below is manually maintained to apply TrimNetconfTrailingWhitespace for banner attributes.
// This prevents Terraform drift caused by trailing whitespace in NETCONF responses.
// See: https://github.com/CiscoDevNet/terraform-provider-iosxe/issues/686

func (data *Banner) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/exec/banner"); value.Exists() {
		data.ExecBanner = types.StringValue(helpers.TrimNetconfTrailingWhitespace(value.String()))
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/login/banner"); value.Exists() {
		data.LoginBanner = types.StringValue(helpers.TrimNetconfTrailingWhitespace(value.String()))
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/prompt-timeout/banner"); value.Exists() {
		data.PromptTimeoutBanner = types.StringValue(helpers.TrimNetconfTrailingWhitespace(value.String()))
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/motd/banner"); value.Exists() {
		data.MotdBanner = types.StringValue(helpers.TrimNetconfTrailingWhitespace(value.String()))
	}
}

// End of manually maintained section.

// Section below is manually maintained to apply TrimNetconfTrailingWhitespace for banner attributes.
// This prevents Terraform drift caused by trailing whitespace in NETCONF responses.
// See: https://github.com/CiscoDevNet/terraform-provider-iosxe/issues/686

func (data *BannerData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/exec/banner"); value.Exists() {
		data.ExecBanner = types.StringValue(helpers.TrimNetconfTrailingWhitespace(value.String()))
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/login/banner"); value.Exists() {
		data.LoginBanner = types.StringValue(helpers.TrimNetconfTrailingWhitespace(value.String()))
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/prompt-timeout/banner"); value.Exists() {
		data.PromptTimeoutBanner = types.StringValue(helpers.TrimNetconfTrailingWhitespace(value.String()))
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/motd/banner"); value.Exists() {
		data.MotdBanner = types.StringValue(helpers.TrimNetconfTrailingWhitespace(value.String()))
	}
}

// End of manually maintained section.

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *Banner) addDeletedItemsXML(ctx context.Context, state Banner, body string) string {
	b := netconf.NewBody(body)
	if !state.MotdBanner.IsNull() && data.MotdBanner.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/motd/banner")
	}
	if !state.PromptTimeoutBanner.IsNull() && data.PromptTimeoutBanner.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/prompt-timeout/banner")
	}
	if !state.LoginBanner.IsNull() && data.LoginBanner.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/login/banner")
	}
	if !state.ExecBanner.IsNull() && data.ExecBanner.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/exec/banner")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *Banner) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	if !data.MotdBanner.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/motd/banner")
	}
	if !data.PromptTimeoutBanner.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/prompt-timeout/banner")
	}
	if !data.LoginBanner.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/login/banner")
	}
	if !data.ExecBanner.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/exec/banner")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
