// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"reflect"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type SLA struct {
	Device    types.String   `tfsdk:"device"`
	Id        types.String   `tfsdk:"id"`
	Entries   []SLAEntries   `tfsdk:"entries"`
	Schedules []SLASchedules `tfsdk:"schedules"`
}
type SLAEntries struct {
	Number              types.Int64  `tfsdk:"number"`
	IcmpEchoDestination types.String `tfsdk:"icmp_echo_destination"`
	IcmpEchoSourceIp    types.String `tfsdk:"icmp_echo_source_ip"`
	IcmpEchoFrequency   types.Int64  `tfsdk:"icmp_echo_frequency"`
}
type SLASchedules struct {
	EntryNumber  types.Int64 `tfsdk:"entry_number"`
	Life         types.Int64 `tfsdk:"life"`
	StartTimeNow types.Bool  `tfsdk:"start_time_now"`
}

type SLAData struct {
	Device    types.String       `tfsdk:"device"`
	Id        types.String       `tfsdk:"id"`
	Entries   []SLAEntriesData   `tfsdk:"entries"`
	Schedules []SLASchedulesData `tfsdk:"schedules"`
}
type SLAEntriesData struct {
	Number              types.Int64  `tfsdk:"number"`
	IcmpEchoDestination types.String `tfsdk:"icmp_echo_destination"`
	IcmpEchoSourceIp    types.String `tfsdk:"icmp_echo_source_ip"`
	IcmpEchoFrequency   types.Int64  `tfsdk:"icmp_echo_frequency"`
}
type SLASchedulesData struct {
	EntryNumber  types.Int64 `tfsdk:"entry_number"`
	Life         types.Int64 `tfsdk:"life"`
	StartTimeNow types.Bool  `tfsdk:"start_time_now"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data SLA) getPath() string {
	return "Cisco-IOS-XE-native:native/ip/Cisco-IOS-XE-sla:sla"
}

func (data SLAData) getPath() string {
	return "Cisco-IOS-XE-native:native/ip/Cisco-IOS-XE-sla:sla"
}

// getXPath returns the XPath for NETCONF operations
func (data SLA) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/ip/Cisco-IOS-XE-sla:sla"
	return path
}

func (data SLAData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/ip/Cisco-IOS-XE-sla:sla"
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data SLA) toBodyXML(ctx context.Context, config SLA) string {
	body := netconf.Body{}
	if len(data.Entries) > 0 {
		for _, item := range data.Entries {
			cBody := netconf.Body{}
			if !item.Number.IsNull() && !item.Number.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "number", strconv.FormatInt(item.Number.ValueInt64(), 10))
			}
			if !item.IcmpEchoDestination.IsNull() && !item.IcmpEchoDestination.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "icmp-echo/destination", item.IcmpEchoDestination.ValueString())
			}
			if !item.IcmpEchoSourceIp.IsNull() && !item.IcmpEchoSourceIp.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "icmp-echo/source-ip", item.IcmpEchoSourceIp.ValueString())
			}
			if !item.IcmpEchoFrequency.IsNull() && !item.IcmpEchoFrequency.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "icmp-echo/frequency", strconv.FormatInt(item.IcmpEchoFrequency.ValueInt64(), 10))
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/entry", cBody.Res())
		}
	}
	if len(data.Schedules) > 0 {
		for _, item := range data.Schedules {
			cBody := netconf.Body{}
			if !item.EntryNumber.IsNull() && !item.EntryNumber.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "entry-number", strconv.FormatInt(item.EntryNumber.ValueInt64(), 10))
			}
			if !item.Life.IsNull() && !item.Life.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "life", strconv.FormatInt(item.Life.ValueInt64(), 10))
			}
			if !item.StartTimeNow.IsNull() && !item.StartTimeNow.IsUnknown() {
				if item.StartTimeNow.ValueBool() {
					cBody = helpers.SetFromXPath(cBody, "start-time/now-config", "")
				} else {
					cBody = helpers.RemoveFromXPath(cBody, "start-time/now-config")
				}
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/schedule", cBody.Res())
		}
	}
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *SLA) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	for i := range data.Entries {
		keys := [...]string{"number"}
		keyValues := [...]string{strconv.FormatInt(data.Entries[i].Number.ValueInt64(), 10)}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/entry").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "number"); value.Exists() && !data.Entries[i].Number.IsNull() {
			data.Entries[i].Number = types.Int64Value(value.Int())
		} else {
			data.Entries[i].Number = types.Int64Null()
		}
		if value := helpers.GetFromXPath(r, "icmp-echo/destination"); value.Exists() && !data.Entries[i].IcmpEchoDestination.IsNull() {
			data.Entries[i].IcmpEchoDestination = types.StringValue(value.String())
		} else {
			data.Entries[i].IcmpEchoDestination = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "icmp-echo/source-ip"); value.Exists() && !data.Entries[i].IcmpEchoSourceIp.IsNull() {
			data.Entries[i].IcmpEchoSourceIp = types.StringValue(value.String())
		} else {
			data.Entries[i].IcmpEchoSourceIp = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "icmp-echo/frequency"); value.Exists() && !data.Entries[i].IcmpEchoFrequency.IsNull() {
			data.Entries[i].IcmpEchoFrequency = types.Int64Value(value.Int())
		} else {
			data.Entries[i].IcmpEchoFrequency = types.Int64Null()
		}
	}
	for i := range data.Schedules {
		keys := [...]string{"entry-number"}
		keyValues := [...]string{strconv.FormatInt(data.Schedules[i].EntryNumber.ValueInt64(), 10)}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/schedule").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "entry-number"); value.Exists() && !data.Schedules[i].EntryNumber.IsNull() {
			data.Schedules[i].EntryNumber = types.Int64Value(value.Int())
		} else {
			data.Schedules[i].EntryNumber = types.Int64Null()
		}
		if value := helpers.GetFromXPath(r, "life"); value.Exists() && !data.Schedules[i].Life.IsNull() {
			data.Schedules[i].Life = types.Int64Value(value.Int())
		} else {
			data.Schedules[i].Life = types.Int64Null()
		}
		if value := helpers.GetFromXPath(r, "start-time/now-config"); !data.Schedules[i].StartTimeNow.IsNull() {
			if value.Exists() {
				data.Schedules[i].StartTimeNow = types.BoolValue(true)
			} else {
				data.Schedules[i].StartTimeNow = types.BoolValue(false)
			}
		} else {
			data.Schedules[i].StartTimeNow = types.BoolNull()
		}
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *SLA) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/entry"); value.Exists() {
		data.Entries = make([]SLAEntries, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := SLAEntries{}
			if cValue := helpers.GetFromXPath(v, "number"); cValue.Exists() {
				item.Number = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "icmp-echo/destination"); cValue.Exists() {
				item.IcmpEchoDestination = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "icmp-echo/source-ip"); cValue.Exists() {
				item.IcmpEchoSourceIp = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "icmp-echo/frequency"); cValue.Exists() {
				item.IcmpEchoFrequency = types.Int64Value(cValue.Int())
			}
			data.Entries = append(data.Entries, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/schedule"); value.Exists() {
		data.Schedules = make([]SLASchedules, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := SLASchedules{}
			if cValue := helpers.GetFromXPath(v, "entry-number"); cValue.Exists() {
				item.EntryNumber = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "life"); cValue.Exists() {
				item.Life = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "start-time/now-config"); cValue.Exists() {
				item.StartTimeNow = types.BoolValue(true)
			} else {
				item.StartTimeNow = types.BoolValue(false)
			}
			data.Schedules = append(data.Schedules, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *SLAData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/entry"); value.Exists() {
		data.Entries = make([]SLAEntriesData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := SLAEntriesData{}
			if cValue := helpers.GetFromXPath(v, "number"); cValue.Exists() {
				item.Number = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "icmp-echo/destination"); cValue.Exists() {
				item.IcmpEchoDestination = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "icmp-echo/source-ip"); cValue.Exists() {
				item.IcmpEchoSourceIp = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "icmp-echo/frequency"); cValue.Exists() {
				item.IcmpEchoFrequency = types.Int64Value(cValue.Int())
			}
			data.Entries = append(data.Entries, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/schedule"); value.Exists() {
		data.Schedules = make([]SLASchedulesData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := SLASchedulesData{}
			if cValue := helpers.GetFromXPath(v, "entry-number"); cValue.Exists() {
				item.EntryNumber = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "life"); cValue.Exists() {
				item.Life = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "start-time/now-config"); cValue.Exists() {
				item.StartTimeNow = types.BoolValue(true)
			} else {
				item.StartTimeNow = types.BoolValue(false)
			}
			data.Schedules = append(data.Schedules, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *SLA) addDeletedItemsXML(ctx context.Context, state SLA, body string) string {
	b := netconf.NewBody(body)
	for i := range state.Schedules {
		stateKeys := [...]string{"entry-number"}
		stateKeyValues := [...]string{strconv.FormatInt(state.Schedules[i].EntryNumber.ValueInt64(), 10)}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.Schedules[i].EntryNumber.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Schedules {
			found = true
			if state.Schedules[i].EntryNumber.ValueInt64() != data.Schedules[j].EntryNumber.ValueInt64() {
				found = false
			}
			if found {
				if !state.Schedules[i].StartTimeNow.IsNull() && data.Schedules[j].StartTimeNow.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/schedule%v/start-time/now-config", predicates))
				}
				if !state.Schedules[i].Life.IsNull() && data.Schedules[j].Life.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/schedule%v/life", predicates))
				}
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/schedule%v", predicates))
		}
	}
	for i := range state.Entries {
		stateKeys := [...]string{"number"}
		stateKeyValues := [...]string{strconv.FormatInt(state.Entries[i].Number.ValueInt64(), 10)}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.Entries[i].Number.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Entries {
			found = true
			if state.Entries[i].Number.ValueInt64() != data.Entries[j].Number.ValueInt64() {
				found = false
			}
			if found {
				if !state.Entries[i].IcmpEchoFrequency.IsNull() && data.Entries[j].IcmpEchoFrequency.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/entry%v/icmp-echo/frequency", predicates))
				}
				if !state.Entries[i].IcmpEchoSourceIp.IsNull() && data.Entries[j].IcmpEchoSourceIp.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/entry%v/icmp-echo/source-ip", predicates))
				}
				if !state.Entries[i].IcmpEchoDestination.IsNull() && data.Entries[j].IcmpEchoDestination.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/entry%v/icmp-echo/destination", predicates))
				}
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/entry%v", predicates))
		}
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *SLA) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	for i := range data.Schedules {
		keys := [...]string{"entry-number"}
		keyValues := [...]string{strconv.FormatInt(data.Schedules[i].EntryNumber.ValueInt64(), 10)}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/schedule%v", predicates))
	}
	for i := range data.Entries {
		keys := [...]string{"number"}
		keyValues := [...]string{strconv.FormatInt(data.Entries[i].Number.ValueInt64(), 10)}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/entry%v", predicates))
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
