// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"
	"reflect"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type ClassMap struct {
	Device                                    types.String                             `tfsdk:"device"`
	Id                                        types.String                             `tfsdk:"id"`
	Name                                      types.String                             `tfsdk:"name"`
	Type                                      types.String                             `tfsdk:"type"`
	Subscriber                                types.Bool                               `tfsdk:"subscriber"`
	Prematch                                  types.String                             `tfsdk:"prematch"`
	MatchAuthorizationStatusAuthorized        types.Bool                               `tfsdk:"match_authorization_status_authorized"`
	MatchResultTypeAaaTimeout                 types.Bool                               `tfsdk:"match_result_type_aaa_timeout"`
	MatchResultTypeSuccess                    types.Bool                               `tfsdk:"match_result_type_success"`
	MatchAuthorizationStatusUnauthorized      types.Bool                               `tfsdk:"match_authorization_status_unauthorized"`
	MatchActivatedServiceTemplates            []ClassMapMatchActivatedServiceTemplates `tfsdk:"match_activated_service_templates"`
	MatchAuthorizingMethodPriorityGreaterThan types.List                               `tfsdk:"match_authorizing_method_priority_greater_than"`
	MatchMethodDot1x                          types.Bool                               `tfsdk:"match_method_dot1x"`
	MatchResultTypeMethodDot1xAuthoritative   types.Bool                               `tfsdk:"match_result_type_method_dot1x_authoritative"`
	MatchResultTypeMethodDot1xAgentNotFound   types.Bool                               `tfsdk:"match_result_type_method_dot1x_agent_not_found"`
	MatchResultTypeMethodDot1xMethodTimeout   types.Bool                               `tfsdk:"match_result_type_method_dot1x_method_timeout"`
	MatchMethodMab                            types.Bool                               `tfsdk:"match_method_mab"`
	MatchResultTypeMethodMabAuthoritative     types.Bool                               `tfsdk:"match_result_type_method_mab_authoritative"`
	MatchDscp                                 types.List                               `tfsdk:"match_dscp"`
	MatchCos                                  types.List                               `tfsdk:"match_cos"`
	Description                               types.String                             `tfsdk:"description"`
	MatchAccessGroupIndexLegacy               types.String                             `tfsdk:"match_access_group_index_legacy"`
	MatchAccessGroupIndexList                 types.List                               `tfsdk:"match_access_group_index_list"`
	MatchAccessGroupName                      types.List                               `tfsdk:"match_access_group_name"`
	MatchIpDscp                               types.List                               `tfsdk:"match_ip_dscp"`
	MatchIpPrecedence                         types.List                               `tfsdk:"match_ip_precedence"`
	MatchProtocol                             []ClassMapMatchProtocol                  `tfsdk:"match_protocol"`
	MatchClassMap                             types.List                               `tfsdk:"match_class_map"`
}
type ClassMapMatchActivatedServiceTemplates struct {
	ServiceName types.String `tfsdk:"service_name"`
}
type ClassMapMatchProtocol struct {
	Protocols types.String `tfsdk:"protocols"`
}

type ClassMapData struct {
	Device                                    types.String                                 `tfsdk:"device"`
	Id                                        types.String                                 `tfsdk:"id"`
	Name                                      types.String                                 `tfsdk:"name"`
	Type                                      types.String                                 `tfsdk:"type"`
	Subscriber                                types.Bool                                   `tfsdk:"subscriber"`
	Prematch                                  types.String                                 `tfsdk:"prematch"`
	MatchAuthorizationStatusAuthorized        types.Bool                                   `tfsdk:"match_authorization_status_authorized"`
	MatchResultTypeAaaTimeout                 types.Bool                                   `tfsdk:"match_result_type_aaa_timeout"`
	MatchResultTypeSuccess                    types.Bool                                   `tfsdk:"match_result_type_success"`
	MatchAuthorizationStatusUnauthorized      types.Bool                                   `tfsdk:"match_authorization_status_unauthorized"`
	MatchActivatedServiceTemplates            []ClassMapMatchActivatedServiceTemplatesData `tfsdk:"match_activated_service_templates"`
	MatchAuthorizingMethodPriorityGreaterThan types.List                                   `tfsdk:"match_authorizing_method_priority_greater_than"`
	MatchMethodDot1x                          types.Bool                                   `tfsdk:"match_method_dot1x"`
	MatchResultTypeMethodDot1xAuthoritative   types.Bool                                   `tfsdk:"match_result_type_method_dot1x_authoritative"`
	MatchResultTypeMethodDot1xAgentNotFound   types.Bool                                   `tfsdk:"match_result_type_method_dot1x_agent_not_found"`
	MatchResultTypeMethodDot1xMethodTimeout   types.Bool                                   `tfsdk:"match_result_type_method_dot1x_method_timeout"`
	MatchMethodMab                            types.Bool                                   `tfsdk:"match_method_mab"`
	MatchResultTypeMethodMabAuthoritative     types.Bool                                   `tfsdk:"match_result_type_method_mab_authoritative"`
	MatchDscp                                 types.List                                   `tfsdk:"match_dscp"`
	MatchCos                                  types.List                                   `tfsdk:"match_cos"`
	Description                               types.String                                 `tfsdk:"description"`
	MatchAccessGroupIndexLegacy               types.String                                 `tfsdk:"match_access_group_index_legacy"`
	MatchAccessGroupIndexList                 types.List                                   `tfsdk:"match_access_group_index_list"`
	MatchAccessGroupName                      types.List                                   `tfsdk:"match_access_group_name"`
	MatchIpDscp                               types.List                                   `tfsdk:"match_ip_dscp"`
	MatchIpPrecedence                         types.List                                   `tfsdk:"match_ip_precedence"`
	MatchProtocol                             []ClassMapMatchProtocolData                  `tfsdk:"match_protocol"`
	MatchClassMap                             types.List                                   `tfsdk:"match_class_map"`
}
type ClassMapMatchActivatedServiceTemplatesData struct {
	ServiceName types.String `tfsdk:"service_name"`
}
type ClassMapMatchProtocolData struct {
	Protocols types.String `tfsdk:"protocols"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data ClassMap) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/policy/Cisco-IOS-XE-policy:class-map=%v", url.QueryEscape(fmt.Sprintf("%v", data.Name.ValueString())))
}

func (data ClassMapData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/policy/Cisco-IOS-XE-policy:class-map=%v", url.QueryEscape(fmt.Sprintf("%v", data.Name.ValueString())))
}

// getXPath returns the XPath for NETCONF operations
func (data ClassMap) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/policy/Cisco-IOS-XE-policy:class-map[name=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Name.ValueString()))
	return path
}

func (data ClassMapData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/policy/Cisco-IOS-XE-policy:class-map[name=%v]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Name.ValueString()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data ClassMap) toBodyXML(ctx context.Context, config ClassMap) string {
	body := netconf.Body{}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/name", data.Name.ValueString())
	}
	if !data.Type.IsNull() && !data.Type.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/type", data.Type.ValueString())
	}
	if !data.Subscriber.IsNull() && !data.Subscriber.IsUnknown() {
		if data.Subscriber.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/subscriber", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/subscriber")
		}
	}
	if !data.Prematch.IsNull() && !data.Prematch.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/prematch", data.Prematch.ValueString())
	}
	if !data.MatchAuthorizationStatusAuthorized.IsNull() && !data.MatchAuthorizationStatusAuthorized.IsUnknown() {
		if data.MatchAuthorizationStatusAuthorized.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/match/authorization-status/authorized", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/match/authorization-status/authorized")
		}
	}
	if !data.MatchResultTypeAaaTimeout.IsNull() && !data.MatchResultTypeAaaTimeout.IsUnknown() {
		if data.MatchResultTypeAaaTimeout.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/match/result-type/aaa-timeout", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/match/result-type/aaa-timeout")
		}
	}
	if !data.MatchResultTypeSuccess.IsNull() && !data.MatchResultTypeSuccess.IsUnknown() {
		if data.MatchResultTypeSuccess.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/match/result-type/success", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/match/result-type/success")
		}
	}
	if !data.MatchAuthorizationStatusUnauthorized.IsNull() && !data.MatchAuthorizationStatusUnauthorized.IsUnknown() {
		if data.MatchAuthorizationStatusUnauthorized.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/match/authorization-status/unauthorized", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/match/authorization-status/unauthorized")
		}
	}
	if len(data.MatchActivatedServiceTemplates) > 0 {
		for _, item := range data.MatchActivatedServiceTemplates {
			cBody := netconf.Body{}
			if !item.ServiceName.IsNull() && !item.ServiceName.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "service-name", item.ServiceName.ValueString())
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/match/activated-service-template", cBody.Res())
		}
	}
	if !data.MatchAuthorizingMethodPriorityGreaterThan.IsNull() && !data.MatchAuthorizingMethodPriorityGreaterThan.IsUnknown() {
		var values []int
		data.MatchAuthorizingMethodPriorityGreaterThan.ElementsAs(ctx, &values, false)
		for _, v := range values {
			body = helpers.AppendFromXPath(body, data.getXPath()+"/match/authorizing-method-priority/greater-than", v)
		}
	}
	if !data.MatchMethodDot1x.IsNull() && !data.MatchMethodDot1x.IsUnknown() {
		if data.MatchMethodDot1x.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/match/method/dot1x", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/match/method/dot1x")
		}
	}
	if !data.MatchResultTypeMethodDot1xAuthoritative.IsNull() && !data.MatchResultTypeMethodDot1xAuthoritative.IsUnknown() {
		if data.MatchResultTypeMethodDot1xAuthoritative.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/match/result-type/method/dot1x/authoritative", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/match/result-type/method/dot1x/authoritative")
		}
	}
	if !data.MatchResultTypeMethodDot1xAgentNotFound.IsNull() && !data.MatchResultTypeMethodDot1xAgentNotFound.IsUnknown() {
		if data.MatchResultTypeMethodDot1xAgentNotFound.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/match/result-type/method/dot1x/agent-not-found", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/match/result-type/method/dot1x/agent-not-found")
		}
	}
	if !data.MatchResultTypeMethodDot1xMethodTimeout.IsNull() && !data.MatchResultTypeMethodDot1xMethodTimeout.IsUnknown() {
		if data.MatchResultTypeMethodDot1xMethodTimeout.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/match/result-type/method/dot1x/method-timeout", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/match/result-type/method/dot1x/method-timeout")
		}
	}
	if !data.MatchMethodMab.IsNull() && !data.MatchMethodMab.IsUnknown() {
		if data.MatchMethodMab.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/match/method/mab", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/match/method/mab")
		}
	}
	if !data.MatchResultTypeMethodMabAuthoritative.IsNull() && !data.MatchResultTypeMethodMabAuthoritative.IsUnknown() {
		if data.MatchResultTypeMethodMabAuthoritative.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/match/result-type/method/mab/authoritative", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/match/result-type/method/mab/authoritative")
		}
	}
	if !data.MatchDscp.IsNull() && !data.MatchDscp.IsUnknown() {
		var values []string
		data.MatchDscp.ElementsAs(ctx, &values, false)
		for _, v := range values {
			body = helpers.AppendFromXPath(body, data.getXPath()+"/match/dscp", v)
		}
	}
	if !data.MatchCos.IsNull() && !data.MatchCos.IsUnknown() {
		var values []int
		data.MatchCos.ElementsAs(ctx, &values, false)
		for _, v := range values {
			body = helpers.AppendFromXPath(body, data.getXPath()+"/match/cos", v)
		}
	}
	if !data.Description.IsNull() && !data.Description.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/description", data.Description.ValueString())
	}
	if !data.MatchAccessGroupIndexLegacy.IsNull() && !data.MatchAccessGroupIndexLegacy.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/match/access-group/index", data.MatchAccessGroupIndexLegacy.ValueString())
	}
	if !data.MatchAccessGroupIndexList.IsNull() && !data.MatchAccessGroupIndexList.IsUnknown() {
		var values []string
		data.MatchAccessGroupIndexList.ElementsAs(ctx, &values, false)
		for _, v := range values {
			body = helpers.AppendFromXPath(body, data.getXPath()+"/match/access-group/index_list", v)
		}
	}
	if !data.MatchAccessGroupName.IsNull() && !data.MatchAccessGroupName.IsUnknown() {
		var values []string
		data.MatchAccessGroupName.ElementsAs(ctx, &values, false)
		for _, v := range values {
			body = helpers.AppendFromXPath(body, data.getXPath()+"/match/access-group/name", v)
		}
	}
	if !data.MatchIpDscp.IsNull() && !data.MatchIpDscp.IsUnknown() {
		var values []string
		data.MatchIpDscp.ElementsAs(ctx, &values, false)
		for _, v := range values {
			body = helpers.AppendFromXPath(body, data.getXPath()+"/match/ip/dscp", v)
		}
	}
	if !data.MatchIpPrecedence.IsNull() && !data.MatchIpPrecedence.IsUnknown() {
		var values []string
		data.MatchIpPrecedence.ElementsAs(ctx, &values, false)
		for _, v := range values {
			body = helpers.AppendFromXPath(body, data.getXPath()+"/match/ip/precedence", v)
		}
	}
	if len(data.MatchProtocol) > 0 {
		for _, item := range data.MatchProtocol {
			cBody := netconf.Body{}
			if !item.Protocols.IsNull() && !item.Protocols.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "protocols", item.Protocols.ValueString())
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/match/protocol/protocols-list", cBody.Res())
		}
	}
	if !data.MatchClassMap.IsNull() && !data.MatchClassMap.IsUnknown() {
		var values []string
		data.MatchClassMap.ElementsAs(ctx, &values, false)
		for _, v := range values {
			body = helpers.AppendFromXPath(body, data.getXPath()+"/match/class-map", v)
		}
	}
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *ClassMap) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/name"); value.Exists() && !data.Name.IsNull() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/type"); value.Exists() && !data.Type.IsNull() {
		data.Type = types.StringValue(value.String())
	} else {
		data.Type = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/subscriber"); !data.Subscriber.IsNull() {
		if value.Exists() {
			data.Subscriber = types.BoolValue(true)
		} else {
			data.Subscriber = types.BoolValue(false)
		}
	} else {
		data.Subscriber = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/prematch"); value.Exists() && !data.Prematch.IsNull() {
		data.Prematch = types.StringValue(value.String())
	} else {
		data.Prematch = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/authorization-status/authorized"); !data.MatchAuthorizationStatusAuthorized.IsNull() {
		if value.Exists() {
			data.MatchAuthorizationStatusAuthorized = types.BoolValue(true)
		} else {
			data.MatchAuthorizationStatusAuthorized = types.BoolValue(false)
		}
	} else {
		data.MatchAuthorizationStatusAuthorized = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/aaa-timeout"); !data.MatchResultTypeAaaTimeout.IsNull() {
		if value.Exists() {
			data.MatchResultTypeAaaTimeout = types.BoolValue(true)
		} else {
			data.MatchResultTypeAaaTimeout = types.BoolValue(false)
		}
	} else {
		data.MatchResultTypeAaaTimeout = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/success"); !data.MatchResultTypeSuccess.IsNull() {
		if value.Exists() {
			data.MatchResultTypeSuccess = types.BoolValue(true)
		} else {
			data.MatchResultTypeSuccess = types.BoolValue(false)
		}
	} else {
		data.MatchResultTypeSuccess = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/authorization-status/unauthorized"); !data.MatchAuthorizationStatusUnauthorized.IsNull() {
		if value.Exists() {
			data.MatchAuthorizationStatusUnauthorized = types.BoolValue(true)
		} else {
			data.MatchAuthorizationStatusUnauthorized = types.BoolValue(false)
		}
	} else {
		data.MatchAuthorizationStatusUnauthorized = types.BoolNull()
	}
	for i := range data.MatchActivatedServiceTemplates {
		keys := [...]string{"service-name"}
		keyValues := [...]string{data.MatchActivatedServiceTemplates[i].ServiceName.ValueString()}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/activated-service-template").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "service-name"); value.Exists() && !data.MatchActivatedServiceTemplates[i].ServiceName.IsNull() {
			data.MatchActivatedServiceTemplates[i].ServiceName = types.StringValue(value.String())
		} else {
			data.MatchActivatedServiceTemplates[i].ServiceName = types.StringNull()
		}
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/authorizing-method-priority/greater-than"); value.Exists() && !data.MatchAuthorizingMethodPriorityGreaterThan.IsNull() {
		data.MatchAuthorizingMethodPriorityGreaterThan = helpers.GetInt64ListXML(value.Array())
	} else {
		data.MatchAuthorizingMethodPriorityGreaterThan = types.ListNull(types.Int64Type)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/method/dot1x"); !data.MatchMethodDot1x.IsNull() {
		if value.Exists() {
			data.MatchMethodDot1x = types.BoolValue(true)
		} else {
			data.MatchMethodDot1x = types.BoolValue(false)
		}
	} else {
		data.MatchMethodDot1x = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/method/dot1x/authoritative"); !data.MatchResultTypeMethodDot1xAuthoritative.IsNull() {
		if value.Exists() {
			data.MatchResultTypeMethodDot1xAuthoritative = types.BoolValue(true)
		} else {
			data.MatchResultTypeMethodDot1xAuthoritative = types.BoolValue(false)
		}
	} else {
		data.MatchResultTypeMethodDot1xAuthoritative = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/method/dot1x/agent-not-found"); !data.MatchResultTypeMethodDot1xAgentNotFound.IsNull() {
		if value.Exists() {
			data.MatchResultTypeMethodDot1xAgentNotFound = types.BoolValue(true)
		} else {
			data.MatchResultTypeMethodDot1xAgentNotFound = types.BoolValue(false)
		}
	} else {
		data.MatchResultTypeMethodDot1xAgentNotFound = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/method/dot1x/method-timeout"); !data.MatchResultTypeMethodDot1xMethodTimeout.IsNull() {
		if value.Exists() {
			data.MatchResultTypeMethodDot1xMethodTimeout = types.BoolValue(true)
		} else {
			data.MatchResultTypeMethodDot1xMethodTimeout = types.BoolValue(false)
		}
	} else {
		data.MatchResultTypeMethodDot1xMethodTimeout = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/method/mab"); !data.MatchMethodMab.IsNull() {
		if value.Exists() {
			data.MatchMethodMab = types.BoolValue(true)
		} else {
			data.MatchMethodMab = types.BoolValue(false)
		}
	} else {
		data.MatchMethodMab = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/method/mab/authoritative"); !data.MatchResultTypeMethodMabAuthoritative.IsNull() {
		if value.Exists() {
			data.MatchResultTypeMethodMabAuthoritative = types.BoolValue(true)
		} else {
			data.MatchResultTypeMethodMabAuthoritative = types.BoolValue(false)
		}
	} else {
		data.MatchResultTypeMethodMabAuthoritative = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/dscp"); value.Exists() && !data.MatchDscp.IsNull() {
		data.MatchDscp = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchDscp = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/cos"); value.Exists() && !data.MatchCos.IsNull() {
		data.MatchCos = helpers.GetInt64ListXML(value.Array())
	} else {
		data.MatchCos = types.ListNull(types.Int64Type)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() && !data.Description.IsNull() {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/access-group/index"); value.Exists() && !data.MatchAccessGroupIndexLegacy.IsNull() {
		data.MatchAccessGroupIndexLegacy = types.StringValue(value.String())
	} else {
		data.MatchAccessGroupIndexLegacy = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/access-group/index_list"); value.Exists() && !data.MatchAccessGroupIndexList.IsNull() {
		data.MatchAccessGroupIndexList = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchAccessGroupIndexList = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/access-group/name"); value.Exists() && !data.MatchAccessGroupName.IsNull() {
		data.MatchAccessGroupName = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchAccessGroupName = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/ip/dscp"); value.Exists() && !data.MatchIpDscp.IsNull() {
		data.MatchIpDscp = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchIpDscp = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/ip/precedence"); value.Exists() && !data.MatchIpPrecedence.IsNull() {
		data.MatchIpPrecedence = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchIpPrecedence = types.ListNull(types.StringType)
	}
	for i := range data.MatchProtocol {
		keys := [...]string{"protocols"}
		keyValues := [...]string{data.MatchProtocol[i].Protocols.ValueString()}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/protocol/protocols-list").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "protocols"); value.Exists() && !data.MatchProtocol[i].Protocols.IsNull() {
			data.MatchProtocol[i].Protocols = types.StringValue(value.String())
		} else {
			data.MatchProtocol[i].Protocols = types.StringNull()
		}
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/class-map"); value.Exists() && !data.MatchClassMap.IsNull() {
		data.MatchClassMap = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchClassMap = types.ListNull(types.StringType)
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *ClassMap) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/type"); value.Exists() {
		data.Type = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/subscriber"); value.Exists() {
		data.Subscriber = types.BoolValue(true)
	} else {
		data.Subscriber = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/prematch"); value.Exists() {
		data.Prematch = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/authorization-status/authorized"); value.Exists() {
		data.MatchAuthorizationStatusAuthorized = types.BoolValue(true)
	} else {
		data.MatchAuthorizationStatusAuthorized = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/aaa-timeout"); value.Exists() {
		data.MatchResultTypeAaaTimeout = types.BoolValue(true)
	} else {
		data.MatchResultTypeAaaTimeout = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/success"); value.Exists() {
		data.MatchResultTypeSuccess = types.BoolValue(true)
	} else {
		data.MatchResultTypeSuccess = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/authorization-status/unauthorized"); value.Exists() {
		data.MatchAuthorizationStatusUnauthorized = types.BoolValue(true)
	} else {
		data.MatchAuthorizationStatusUnauthorized = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/activated-service-template"); value.Exists() {
		data.MatchActivatedServiceTemplates = make([]ClassMapMatchActivatedServiceTemplates, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := ClassMapMatchActivatedServiceTemplates{}
			if cValue := helpers.GetFromXPath(v, "service-name"); cValue.Exists() {
				item.ServiceName = types.StringValue(cValue.String())
			}
			data.MatchActivatedServiceTemplates = append(data.MatchActivatedServiceTemplates, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/authorizing-method-priority/greater-than"); value.Exists() {
		data.MatchAuthorizingMethodPriorityGreaterThan = helpers.GetInt64ListXML(value.Array())
	} else {
		data.MatchAuthorizingMethodPriorityGreaterThan = types.ListNull(types.Int64Type)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/method/dot1x"); value.Exists() {
		data.MatchMethodDot1x = types.BoolValue(true)
	} else {
		data.MatchMethodDot1x = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/method/dot1x/authoritative"); value.Exists() {
		data.MatchResultTypeMethodDot1xAuthoritative = types.BoolValue(true)
	} else {
		data.MatchResultTypeMethodDot1xAuthoritative = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/method/dot1x/agent-not-found"); value.Exists() {
		data.MatchResultTypeMethodDot1xAgentNotFound = types.BoolValue(true)
	} else {
		data.MatchResultTypeMethodDot1xAgentNotFound = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/method/dot1x/method-timeout"); value.Exists() {
		data.MatchResultTypeMethodDot1xMethodTimeout = types.BoolValue(true)
	} else {
		data.MatchResultTypeMethodDot1xMethodTimeout = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/method/mab"); value.Exists() {
		data.MatchMethodMab = types.BoolValue(true)
	} else {
		data.MatchMethodMab = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/method/mab/authoritative"); value.Exists() {
		data.MatchResultTypeMethodMabAuthoritative = types.BoolValue(true)
	} else {
		data.MatchResultTypeMethodMabAuthoritative = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/dscp"); value.Exists() {
		data.MatchDscp = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchDscp = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/cos"); value.Exists() {
		data.MatchCos = helpers.GetInt64ListXML(value.Array())
	} else {
		data.MatchCos = types.ListNull(types.Int64Type)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/access-group/index"); value.Exists() {
		data.MatchAccessGroupIndexLegacy = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/access-group/index_list"); value.Exists() {
		data.MatchAccessGroupIndexList = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchAccessGroupIndexList = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/access-group/name"); value.Exists() {
		data.MatchAccessGroupName = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchAccessGroupName = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/ip/dscp"); value.Exists() {
		data.MatchIpDscp = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchIpDscp = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/ip/precedence"); value.Exists() {
		data.MatchIpPrecedence = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchIpPrecedence = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/protocol/protocols-list"); value.Exists() {
		data.MatchProtocol = make([]ClassMapMatchProtocol, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := ClassMapMatchProtocol{}
			if cValue := helpers.GetFromXPath(v, "protocols"); cValue.Exists() {
				item.Protocols = types.StringValue(cValue.String())
			}
			data.MatchProtocol = append(data.MatchProtocol, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/class-map"); value.Exists() {
		data.MatchClassMap = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchClassMap = types.ListNull(types.StringType)
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *ClassMapData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/type"); value.Exists() {
		data.Type = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/subscriber"); value.Exists() {
		data.Subscriber = types.BoolValue(true)
	} else {
		data.Subscriber = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/prematch"); value.Exists() {
		data.Prematch = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/authorization-status/authorized"); value.Exists() {
		data.MatchAuthorizationStatusAuthorized = types.BoolValue(true)
	} else {
		data.MatchAuthorizationStatusAuthorized = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/aaa-timeout"); value.Exists() {
		data.MatchResultTypeAaaTimeout = types.BoolValue(true)
	} else {
		data.MatchResultTypeAaaTimeout = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/success"); value.Exists() {
		data.MatchResultTypeSuccess = types.BoolValue(true)
	} else {
		data.MatchResultTypeSuccess = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/authorization-status/unauthorized"); value.Exists() {
		data.MatchAuthorizationStatusUnauthorized = types.BoolValue(true)
	} else {
		data.MatchAuthorizationStatusUnauthorized = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/activated-service-template"); value.Exists() {
		data.MatchActivatedServiceTemplates = make([]ClassMapMatchActivatedServiceTemplatesData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := ClassMapMatchActivatedServiceTemplatesData{}
			if cValue := helpers.GetFromXPath(v, "service-name"); cValue.Exists() {
				item.ServiceName = types.StringValue(cValue.String())
			}
			data.MatchActivatedServiceTemplates = append(data.MatchActivatedServiceTemplates, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/authorizing-method-priority/greater-than"); value.Exists() {
		data.MatchAuthorizingMethodPriorityGreaterThan = helpers.GetInt64ListXML(value.Array())
	} else {
		data.MatchAuthorizingMethodPriorityGreaterThan = types.ListNull(types.Int64Type)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/method/dot1x"); value.Exists() {
		data.MatchMethodDot1x = types.BoolValue(true)
	} else {
		data.MatchMethodDot1x = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/method/dot1x/authoritative"); value.Exists() {
		data.MatchResultTypeMethodDot1xAuthoritative = types.BoolValue(true)
	} else {
		data.MatchResultTypeMethodDot1xAuthoritative = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/method/dot1x/agent-not-found"); value.Exists() {
		data.MatchResultTypeMethodDot1xAgentNotFound = types.BoolValue(true)
	} else {
		data.MatchResultTypeMethodDot1xAgentNotFound = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/method/dot1x/method-timeout"); value.Exists() {
		data.MatchResultTypeMethodDot1xMethodTimeout = types.BoolValue(true)
	} else {
		data.MatchResultTypeMethodDot1xMethodTimeout = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/method/mab"); value.Exists() {
		data.MatchMethodMab = types.BoolValue(true)
	} else {
		data.MatchMethodMab = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/result-type/method/mab/authoritative"); value.Exists() {
		data.MatchResultTypeMethodMabAuthoritative = types.BoolValue(true)
	} else {
		data.MatchResultTypeMethodMabAuthoritative = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/dscp"); value.Exists() {
		data.MatchDscp = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchDscp = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/cos"); value.Exists() {
		data.MatchCos = helpers.GetInt64ListXML(value.Array())
	} else {
		data.MatchCos = types.ListNull(types.Int64Type)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/access-group/index"); value.Exists() {
		data.MatchAccessGroupIndexLegacy = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/access-group/index_list"); value.Exists() {
		data.MatchAccessGroupIndexList = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchAccessGroupIndexList = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/access-group/name"); value.Exists() {
		data.MatchAccessGroupName = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchAccessGroupName = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/ip/dscp"); value.Exists() {
		data.MatchIpDscp = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchIpDscp = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/ip/precedence"); value.Exists() {
		data.MatchIpPrecedence = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchIpPrecedence = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/protocol/protocols-list"); value.Exists() {
		data.MatchProtocol = make([]ClassMapMatchProtocolData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := ClassMapMatchProtocolData{}
			if cValue := helpers.GetFromXPath(v, "protocols"); cValue.Exists() {
				item.Protocols = types.StringValue(cValue.String())
			}
			data.MatchProtocol = append(data.MatchProtocol, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/match/class-map"); value.Exists() {
		data.MatchClassMap = helpers.GetStringListXML(value.Array())
	} else {
		data.MatchClassMap = types.ListNull(types.StringType)
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *ClassMap) addDeletedItemsXML(ctx context.Context, state ClassMap, body string) string {
	b := netconf.NewBody(body)
	if !state.MatchClassMap.IsNull() {
		if data.MatchClassMap.IsNull() {
			var values []string
			state.MatchClassMap.ElementsAs(ctx, &values, false)
			for _, v := range values {
				b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/class-map[.=%v]", v))
			}
		} else {
			var dataValues, stateValues []string
			data.MatchClassMap.ElementsAs(ctx, &dataValues, false)
			state.MatchClassMap.ElementsAs(ctx, &stateValues, false)
			for _, v := range stateValues {
				found := false
				for _, vv := range dataValues {
					if v == vv {
						found = true
						break
					}
				}
				if !found {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/class-map[.=%v]", v))
				}
			}
		}
	}
	for i := range state.MatchProtocol {
		stateKeys := [...]string{"protocols"}
		stateKeyValues := [...]string{state.MatchProtocol[i].Protocols.ValueString()}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.MatchProtocol[i].Protocols.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.MatchProtocol {
			found = true
			if state.MatchProtocol[i].Protocols.ValueString() != data.MatchProtocol[j].Protocols.ValueString() {
				found = false
			}
			if found {
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/protocol/protocols-list%v", predicates))
		}
	}
	if !state.MatchIpPrecedence.IsNull() {
		if data.MatchIpPrecedence.IsNull() {
			var values []string
			state.MatchIpPrecedence.ElementsAs(ctx, &values, false)
			for _, v := range values {
				b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/ip/precedence[.=%v]", v))
			}
		} else {
			var dataValues, stateValues []string
			data.MatchIpPrecedence.ElementsAs(ctx, &dataValues, false)
			state.MatchIpPrecedence.ElementsAs(ctx, &stateValues, false)
			for _, v := range stateValues {
				found := false
				for _, vv := range dataValues {
					if v == vv {
						found = true
						break
					}
				}
				if !found {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/ip/precedence[.=%v]", v))
				}
			}
		}
	}
	if !state.MatchIpDscp.IsNull() {
		if data.MatchIpDscp.IsNull() {
			var values []string
			state.MatchIpDscp.ElementsAs(ctx, &values, false)
			for _, v := range values {
				b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/ip/dscp[.=%v]", v))
			}
		} else {
			var dataValues, stateValues []string
			data.MatchIpDscp.ElementsAs(ctx, &dataValues, false)
			state.MatchIpDscp.ElementsAs(ctx, &stateValues, false)
			for _, v := range stateValues {
				found := false
				for _, vv := range dataValues {
					if v == vv {
						found = true
						break
					}
				}
				if !found {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/ip/dscp[.=%v]", v))
				}
			}
		}
	}
	if !state.MatchAccessGroupName.IsNull() {
		if data.MatchAccessGroupName.IsNull() {
			var values []string
			state.MatchAccessGroupName.ElementsAs(ctx, &values, false)
			for _, v := range values {
				b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/access-group/name[.=%v]", v))
			}
		} else {
			var dataValues, stateValues []string
			data.MatchAccessGroupName.ElementsAs(ctx, &dataValues, false)
			state.MatchAccessGroupName.ElementsAs(ctx, &stateValues, false)
			for _, v := range stateValues {
				found := false
				for _, vv := range dataValues {
					if v == vv {
						found = true
						break
					}
				}
				if !found {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/access-group/name[.=%v]", v))
				}
			}
		}
	}
	if !state.MatchAccessGroupIndexList.IsNull() {
		if data.MatchAccessGroupIndexList.IsNull() {
			var values []string
			state.MatchAccessGroupIndexList.ElementsAs(ctx, &values, false)
			for _, v := range values {
				b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/access-group/index_list[.=%v]", v))
			}
		} else {
			var dataValues, stateValues []string
			data.MatchAccessGroupIndexList.ElementsAs(ctx, &dataValues, false)
			state.MatchAccessGroupIndexList.ElementsAs(ctx, &stateValues, false)
			for _, v := range stateValues {
				found := false
				for _, vv := range dataValues {
					if v == vv {
						found = true
						break
					}
				}
				if !found {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/access-group/index_list[.=%v]", v))
				}
			}
		}
	}
	if !state.MatchAccessGroupIndexLegacy.IsNull() && data.MatchAccessGroupIndexLegacy.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/match/access-group/index")
	}
	if !state.Description.IsNull() && data.Description.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/description")
	}
	if !state.MatchCos.IsNull() {
		if data.MatchCos.IsNull() {
			var values []string
			state.MatchCos.ElementsAs(ctx, &values, false)
			for _, v := range values {
				b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/cos[.=%v]", v))
			}
		} else {
			var dataValues, stateValues []int
			data.MatchCos.ElementsAs(ctx, &dataValues, false)
			state.MatchCos.ElementsAs(ctx, &stateValues, false)
			for _, v := range stateValues {
				found := false
				for _, vv := range dataValues {
					if v == vv {
						found = true
						break
					}
				}
				if !found {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/cos[.=%v]", v))
				}
			}
		}
	}
	if !state.MatchDscp.IsNull() {
		if data.MatchDscp.IsNull() {
			var values []string
			state.MatchDscp.ElementsAs(ctx, &values, false)
			for _, v := range values {
				b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/dscp[.=%v]", v))
			}
		} else {
			var dataValues, stateValues []string
			data.MatchDscp.ElementsAs(ctx, &dataValues, false)
			state.MatchDscp.ElementsAs(ctx, &stateValues, false)
			for _, v := range stateValues {
				found := false
				for _, vv := range dataValues {
					if v == vv {
						found = true
						break
					}
				}
				if !found {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/dscp[.=%v]", v))
				}
			}
		}
	}
	if !state.MatchResultTypeMethodMabAuthoritative.IsNull() && data.MatchResultTypeMethodMabAuthoritative.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/match/result-type/method/mab/authoritative")
	}
	if !state.MatchMethodMab.IsNull() && data.MatchMethodMab.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/match/method/mab")
	}
	if !state.MatchResultTypeMethodDot1xMethodTimeout.IsNull() && data.MatchResultTypeMethodDot1xMethodTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/match/result-type/method/dot1x/method-timeout")
	}
	if !state.MatchResultTypeMethodDot1xAgentNotFound.IsNull() && data.MatchResultTypeMethodDot1xAgentNotFound.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/match/result-type/method/dot1x/agent-not-found")
	}
	if !state.MatchResultTypeMethodDot1xAuthoritative.IsNull() && data.MatchResultTypeMethodDot1xAuthoritative.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/match/result-type/method/dot1x/authoritative")
	}
	if !state.MatchMethodDot1x.IsNull() && data.MatchMethodDot1x.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/match/method/dot1x")
	}
	if !state.MatchAuthorizingMethodPriorityGreaterThan.IsNull() {
		if data.MatchAuthorizingMethodPriorityGreaterThan.IsNull() {
			var values []string
			state.MatchAuthorizingMethodPriorityGreaterThan.ElementsAs(ctx, &values, false)
			for _, v := range values {
				b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/authorizing-method-priority/greater-than[.=%v]", v))
			}
		} else {
			var dataValues, stateValues []int
			data.MatchAuthorizingMethodPriorityGreaterThan.ElementsAs(ctx, &dataValues, false)
			state.MatchAuthorizingMethodPriorityGreaterThan.ElementsAs(ctx, &stateValues, false)
			for _, v := range stateValues {
				found := false
				for _, vv := range dataValues {
					if v == vv {
						found = true
						break
					}
				}
				if !found {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/authorizing-method-priority/greater-than[.=%v]", v))
				}
			}
		}
	}
	for i := range state.MatchActivatedServiceTemplates {
		stateKeys := [...]string{"service-name"}
		stateKeyValues := [...]string{state.MatchActivatedServiceTemplates[i].ServiceName.ValueString()}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.MatchActivatedServiceTemplates[i].ServiceName.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.MatchActivatedServiceTemplates {
			found = true
			if state.MatchActivatedServiceTemplates[i].ServiceName.ValueString() != data.MatchActivatedServiceTemplates[j].ServiceName.ValueString() {
				found = false
			}
			if found {
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/match/activated-service-template%v", predicates))
		}
	}
	if !state.MatchAuthorizationStatusUnauthorized.IsNull() && data.MatchAuthorizationStatusUnauthorized.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/match/authorization-status/unauthorized")
	}
	if !state.MatchResultTypeSuccess.IsNull() && data.MatchResultTypeSuccess.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/match/result-type/success")
	}
	if !state.MatchResultTypeAaaTimeout.IsNull() && data.MatchResultTypeAaaTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/match/result-type/aaa-timeout")
	}
	if !state.MatchAuthorizationStatusAuthorized.IsNull() && data.MatchAuthorizationStatusAuthorized.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/match/authorization-status/authorized")
	}
	if !state.Prematch.IsNull() && data.Prematch.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/prematch")
	}
	if !state.Subscriber.IsNull() && data.Subscriber.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/subscriber")
	}
	if !state.Type.IsNull() && data.Type.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/type")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *ClassMap) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	if !data.MatchClassMap.IsNull() {
		var values []string
		data.MatchClassMap.ElementsAs(ctx, &values, false)
		for _, v := range values {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/match/class-map[.=%v]", v))
		}
	}
	for i := range data.MatchProtocol {
		keys := [...]string{"protocols"}
		keyValues := [...]string{data.MatchProtocol[i].Protocols.ValueString()}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/match/protocol/protocols-list%v", predicates))
	}
	if !data.MatchIpPrecedence.IsNull() {
		var values []string
		data.MatchIpPrecedence.ElementsAs(ctx, &values, false)
		for _, v := range values {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/match/ip/precedence[.=%v]", v))
		}
	}
	if !data.MatchIpDscp.IsNull() {
		var values []string
		data.MatchIpDscp.ElementsAs(ctx, &values, false)
		for _, v := range values {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/match/ip/dscp[.=%v]", v))
		}
	}
	if !data.MatchAccessGroupName.IsNull() {
		var values []string
		data.MatchAccessGroupName.ElementsAs(ctx, &values, false)
		for _, v := range values {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/match/access-group/name[.=%v]", v))
		}
	}
	if !data.MatchAccessGroupIndexList.IsNull() {
		var values []string
		data.MatchAccessGroupIndexList.ElementsAs(ctx, &values, false)
		for _, v := range values {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/match/access-group/index_list[.=%v]", v))
		}
	}
	if !data.MatchAccessGroupIndexLegacy.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/match/access-group/index")
	}
	if !data.Description.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/description")
	}
	if !data.MatchCos.IsNull() {
		var values []int64
		data.MatchCos.ElementsAs(ctx, &values, false)
		for _, v := range values {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/match/cos[.=%v]", v))
		}
	}
	if !data.MatchDscp.IsNull() {
		var values []string
		data.MatchDscp.ElementsAs(ctx, &values, false)
		for _, v := range values {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/match/dscp[.=%v]", v))
		}
	}
	if !data.MatchResultTypeMethodMabAuthoritative.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/match/result-type/method/mab/authoritative")
	}
	if !data.MatchMethodMab.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/match/method/mab")
	}
	if !data.MatchResultTypeMethodDot1xMethodTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/match/result-type/method/dot1x/method-timeout")
	}
	if !data.MatchResultTypeMethodDot1xAgentNotFound.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/match/result-type/method/dot1x/agent-not-found")
	}
	if !data.MatchResultTypeMethodDot1xAuthoritative.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/match/result-type/method/dot1x/authoritative")
	}
	if !data.MatchMethodDot1x.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/match/method/dot1x")
	}
	if !data.MatchAuthorizingMethodPriorityGreaterThan.IsNull() {
		var values []int64
		data.MatchAuthorizingMethodPriorityGreaterThan.ElementsAs(ctx, &values, false)
		for _, v := range values {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/match/authorizing-method-priority/greater-than[.=%v]", v))
		}
	}
	for i := range data.MatchActivatedServiceTemplates {
		keys := [...]string{"service-name"}
		keyValues := [...]string{data.MatchActivatedServiceTemplates[i].ServiceName.ValueString()}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/match/activated-service-template%v", predicates))
	}
	if !data.MatchAuthorizationStatusUnauthorized.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/match/authorization-status/unauthorized")
	}
	if !data.MatchResultTypeSuccess.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/match/result-type/success")
	}
	if !data.MatchResultTypeAaaTimeout.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/match/result-type/aaa-timeout")
	}
	if !data.MatchAuthorizationStatusAuthorized.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/match/authorization-status/authorized")
	}
	if !data.Prematch.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/prematch")
	}
	if !data.Subscriber.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/subscriber")
	}
	if !data.Type.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/type")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
