// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"context"
	"fmt"
	"net/url"
	"reflect"
	"strconv"

	"github.com/CiscoDevNet/terraform-provider-iosxe/internal/provider/helpers"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/netascode/go-netconf"
	"github.com/netascode/xmldot"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin types
type DHCPPool struct {
	Device                 types.String                `tfsdk:"device"`
	Id                     types.String                `tfsdk:"id"`
	DeleteMode             types.String                `tfsdk:"delete_mode"`
	Name                   types.String                `tfsdk:"name"`
	Vrf                    types.String                `tfsdk:"vrf"`
	DomainName             types.String                `tfsdk:"domain_name"`
	Bootfile               types.String                `tfsdk:"bootfile"`
	ClientName             types.String                `tfsdk:"client_name"`
	NetworkNumber          types.String                `tfsdk:"network_number"`
	NetworkMask            types.String                `tfsdk:"network_mask"`
	SecondaryNetworks      []DHCPPoolSecondaryNetworks `tfsdk:"secondary_networks"`
	HostNumber             types.String                `tfsdk:"host_number"`
	HostMask               types.String                `tfsdk:"host_mask"`
	DefaultRouters         types.List                  `tfsdk:"default_routers"`
	DnsServers             types.List                  `tfsdk:"dns_servers"`
	NextServers            types.List                  `tfsdk:"next_servers"`
	LeaseDays              types.Int64                 `tfsdk:"lease_days"`
	LeaseHours             types.Int64                 `tfsdk:"lease_hours"`
	LeaseMinutes           types.Int64                 `tfsdk:"lease_minutes"`
	LeaseInfinite          types.Bool                  `tfsdk:"lease_infinite"`
	UtilizationMarkHigh    types.Int64                 `tfsdk:"utilization_mark_high"`
	UtilizationMarkHighLog types.Bool                  `tfsdk:"utilization_mark_high_log"`
	UtilizationMarkLow     types.Int64                 `tfsdk:"utilization_mark_low"`
	UtilizationMarkLowLog  types.Bool                  `tfsdk:"utilization_mark_low_log"`
	SubnetPrefixLength     types.Int64                 `tfsdk:"subnet_prefix_length"`
	Options                []DHCPPoolOptions           `tfsdk:"options"`
}
type DHCPPoolSecondaryNetworks struct {
	Number    types.String `tfsdk:"number"`
	Mask      types.String `tfsdk:"mask"`
	Secondary types.Bool   `tfsdk:"secondary"`
}
type DHCPPoolOptions struct {
	OptionCode types.Int64  `tfsdk:"option_code"`
	Ascii      types.String `tfsdk:"ascii"`
	Hex        types.String `tfsdk:"hex"`
	Ip         types.List   `tfsdk:"ip"`
	IpLegacy   types.List   `tfsdk:"ip_legacy"`
}

type DHCPPoolData struct {
	Device                 types.String                    `tfsdk:"device"`
	Id                     types.String                    `tfsdk:"id"`
	Name                   types.String                    `tfsdk:"name"`
	Vrf                    types.String                    `tfsdk:"vrf"`
	DomainName             types.String                    `tfsdk:"domain_name"`
	Bootfile               types.String                    `tfsdk:"bootfile"`
	ClientName             types.String                    `tfsdk:"client_name"`
	NetworkNumber          types.String                    `tfsdk:"network_number"`
	NetworkMask            types.String                    `tfsdk:"network_mask"`
	SecondaryNetworks      []DHCPPoolSecondaryNetworksData `tfsdk:"secondary_networks"`
	HostNumber             types.String                    `tfsdk:"host_number"`
	HostMask               types.String                    `tfsdk:"host_mask"`
	DefaultRouters         types.List                      `tfsdk:"default_routers"`
	DnsServers             types.List                      `tfsdk:"dns_servers"`
	NextServers            types.List                      `tfsdk:"next_servers"`
	LeaseDays              types.Int64                     `tfsdk:"lease_days"`
	LeaseHours             types.Int64                     `tfsdk:"lease_hours"`
	LeaseMinutes           types.Int64                     `tfsdk:"lease_minutes"`
	LeaseInfinite          types.Bool                      `tfsdk:"lease_infinite"`
	UtilizationMarkHigh    types.Int64                     `tfsdk:"utilization_mark_high"`
	UtilizationMarkHighLog types.Bool                      `tfsdk:"utilization_mark_high_log"`
	UtilizationMarkLow     types.Int64                     `tfsdk:"utilization_mark_low"`
	UtilizationMarkLowLog  types.Bool                      `tfsdk:"utilization_mark_low_log"`
	SubnetPrefixLength     types.Int64                     `tfsdk:"subnet_prefix_length"`
	Options                []DHCPPoolOptionsData           `tfsdk:"options"`
}
type DHCPPoolSecondaryNetworksData struct {
	Number    types.String `tfsdk:"number"`
	Mask      types.String `tfsdk:"mask"`
	Secondary types.Bool   `tfsdk:"secondary"`
}
type DHCPPoolOptionsData struct {
	OptionCode types.Int64  `tfsdk:"option_code"`
	Ascii      types.String `tfsdk:"ascii"`
	Hex        types.String `tfsdk:"hex"`
	Ip         types.List   `tfsdk:"ip"`
	IpLegacy   types.List   `tfsdk:"ip_legacy"`
}

// End of section. //template:end types

// Section below is generated&owned by "gen/generator.go". //template:begin getPath

func (data DHCPPool) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/ip/dhcp/Cisco-IOS-XE-dhcp:pool=%s", url.QueryEscape(fmt.Sprintf("%v", data.Name.ValueString())))
}

func (data DHCPPoolData) getPath() string {
	return fmt.Sprintf("Cisco-IOS-XE-native:native/ip/dhcp/Cisco-IOS-XE-dhcp:pool=%s", url.QueryEscape(fmt.Sprintf("%v", data.Name.ValueString())))
}

// getXPath returns the XPath for NETCONF operations
func (data DHCPPool) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/ip/dhcp/Cisco-IOS-XE-dhcp:pool[id=%s]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Name.ValueString()))
	return path
}

func (data DHCPPoolData) getXPath() string {
	path := "/Cisco-IOS-XE-native:native/ip/dhcp/Cisco-IOS-XE-dhcp:pool[id=%s]"
	path = fmt.Sprintf(path, fmt.Sprintf("%v", data.Name.ValueString()))
	return path
}

// End of section. //template:end getPath

// Section below is generated&owned by "gen/generator.go". //template:begin toBodyXML

func (data DHCPPool) toBodyXML(ctx context.Context, config DHCPPool) string {
	body := netconf.Body{}
	if !data.Name.IsNull() && !data.Name.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/id", data.Name.ValueString())
	}
	if !data.Vrf.IsNull() && !data.Vrf.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/vrf", data.Vrf.ValueString())
	}
	if !data.DomainName.IsNull() && !data.DomainName.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/domain-name", data.DomainName.ValueString())
	}
	if !data.Bootfile.IsNull() && !data.Bootfile.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/bootfile", data.Bootfile.ValueString())
	}
	if !data.ClientName.IsNull() && !data.ClientName.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/client-name", data.ClientName.ValueString())
	}
	if !data.NetworkNumber.IsNull() && !data.NetworkNumber.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/network/primary-network/number", data.NetworkNumber.ValueString())
	}
	if !data.NetworkMask.IsNull() && !data.NetworkMask.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/network/primary-network/mask", data.NetworkMask.ValueString())
	}
	if len(data.SecondaryNetworks) > 0 {
		for _, item := range data.SecondaryNetworks {
			cBody := netconf.Body{}
			if !item.Number.IsNull() && !item.Number.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "number", item.Number.ValueString())
			}
			if !item.Mask.IsNull() && !item.Mask.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "mask", item.Mask.ValueString())
			}
			if !item.Secondary.IsNull() && !item.Secondary.IsUnknown() {
				if item.Secondary.ValueBool() {
					cBody = helpers.SetFromXPath(cBody, "secondary", "")
				} else {
					cBody = helpers.RemoveFromXPath(cBody, "secondary")
				}
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/network/secondary-network", cBody.Res())
		}
	}
	if !data.HostNumber.IsNull() && !data.HostNumber.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/host/number", data.HostNumber.ValueString())
	}
	if !data.HostMask.IsNull() && !data.HostMask.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/host/mask", data.HostMask.ValueString())
	}
	if !data.DefaultRouters.IsNull() && !data.DefaultRouters.IsUnknown() {
		var values []string
		data.DefaultRouters.ElementsAs(ctx, &values, false)
		for _, v := range values {
			body = helpers.AppendFromXPath(body, data.getXPath()+"/default-router/default-router-list", v)
		}
	}
	if !data.DnsServers.IsNull() && !data.DnsServers.IsUnknown() {
		var values []string
		data.DnsServers.ElementsAs(ctx, &values, false)
		for _, v := range values {
			body = helpers.AppendFromXPath(body, data.getXPath()+"/dns-server/dns-server-list", v)
		}
	}
	if !data.NextServers.IsNull() && !data.NextServers.IsUnknown() {
		var values []string
		data.NextServers.ElementsAs(ctx, &values, false)
		for _, v := range values {
			body = helpers.AppendFromXPath(body, data.getXPath()+"/next-server", v)
		}
	}
	if !data.LeaseDays.IsNull() && !data.LeaseDays.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/lease/lease-value/days", strconv.FormatInt(data.LeaseDays.ValueInt64(), 10))
	}
	if !data.LeaseHours.IsNull() && !data.LeaseHours.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/lease/lease-value/hours", strconv.FormatInt(data.LeaseHours.ValueInt64(), 10))
	}
	if !data.LeaseMinutes.IsNull() && !data.LeaseMinutes.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/lease/lease-value/minutes", strconv.FormatInt(data.LeaseMinutes.ValueInt64(), 10))
	}
	if !data.LeaseInfinite.IsNull() && !data.LeaseInfinite.IsUnknown() {
		if data.LeaseInfinite.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/lease/infinite", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/lease/infinite")
		}
	}
	if !data.UtilizationMarkHigh.IsNull() && !data.UtilizationMarkHigh.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/utilization/mark/high/high-value", strconv.FormatInt(data.UtilizationMarkHigh.ValueInt64(), 10))
	}
	if !data.UtilizationMarkHighLog.IsNull() && !data.UtilizationMarkHighLog.IsUnknown() {
		if data.UtilizationMarkHighLog.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/utilization/mark/high/log", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/utilization/mark/high/log")
		}
	}
	if !data.UtilizationMarkLow.IsNull() && !data.UtilizationMarkLow.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/utilization/mark/low/low-value", strconv.FormatInt(data.UtilizationMarkLow.ValueInt64(), 10))
	}
	if !data.UtilizationMarkLowLog.IsNull() && !data.UtilizationMarkLowLog.IsUnknown() {
		if data.UtilizationMarkLowLog.ValueBool() {
			body = helpers.SetFromXPath(body, data.getXPath()+"/utilization/mark/low/log", "")
		} else {
			body = helpers.RemoveFromXPath(body, data.getXPath()+"/utilization/mark/low/log")
		}
	}
	if !data.SubnetPrefixLength.IsNull() && !data.SubnetPrefixLength.IsUnknown() {
		body = helpers.SetFromXPath(body, data.getXPath()+"/subnet/prefix-length", strconv.FormatInt(data.SubnetPrefixLength.ValueInt64(), 10))
	}
	if len(data.Options) > 0 {
		for _, item := range data.Options {
			cBody := netconf.Body{}
			if !item.OptionCode.IsNull() && !item.OptionCode.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "option-range", strconv.FormatInt(item.OptionCode.ValueInt64(), 10))
			}
			if !item.Ascii.IsNull() && !item.Ascii.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "ascii-new", item.Ascii.ValueString())
			}
			if !item.Hex.IsNull() && !item.Hex.IsUnknown() {
				cBody = helpers.SetFromXPath(cBody, "hex-new/hex-line", item.Hex.ValueString())
			}
			if !item.Ip.IsNull() && !item.Ip.IsUnknown() {
				var values []string
				item.Ip.ElementsAs(ctx, &values, false)
				for _, v := range values {
					cBody = helpers.AppendFromXPath(cBody, "ip-ordered", v)
				}
			}
			if !item.IpLegacy.IsNull() && !item.IpLegacy.IsUnknown() {
				var values []string
				item.IpLegacy.ElementsAs(ctx, &values, false)
				for _, v := range values {
					cBody = helpers.AppendFromXPath(cBody, "ip-new", v)
				}
			}
			body = helpers.SetRawFromXPath(body, data.getXPath()+"/option/option-range", cBody.Res())
		}
	}
	bodyString, err := body.String()
	if err != nil {
		tflog.Error(ctx, fmt.Sprintf("Error converting body to string: %s", err))
	}
	return bodyString
}

// End of section. //template:end toBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin updateFromBodyXML

func (data *DHCPPool) updateFromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/id"); value.Exists() && !data.Name.IsNull() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/vrf"); value.Exists() && !data.Vrf.IsNull() {
		data.Vrf = types.StringValue(value.String())
	} else {
		data.Vrf = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/domain-name"); value.Exists() && !data.DomainName.IsNull() {
		data.DomainName = types.StringValue(value.String())
	} else {
		data.DomainName = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/bootfile"); value.Exists() && !data.Bootfile.IsNull() {
		data.Bootfile = types.StringValue(value.String())
	} else {
		data.Bootfile = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/client-name"); value.Exists() && !data.ClientName.IsNull() {
		data.ClientName = types.StringValue(value.String())
	} else {
		data.ClientName = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/network/primary-network/number"); value.Exists() && !data.NetworkNumber.IsNull() {
		data.NetworkNumber = types.StringValue(value.String())
	} else {
		data.NetworkNumber = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/network/primary-network/mask"); value.Exists() && !data.NetworkMask.IsNull() {
		data.NetworkMask = types.StringValue(value.String())
	} else {
		data.NetworkMask = types.StringNull()
	}
	for i := range data.SecondaryNetworks {
		keys := [...]string{"number"}
		keyValues := [...]string{data.SecondaryNetworks[i].Number.ValueString()}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/network/secondary-network").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "number"); value.Exists() && !data.SecondaryNetworks[i].Number.IsNull() {
			data.SecondaryNetworks[i].Number = types.StringValue(value.String())
		} else {
			data.SecondaryNetworks[i].Number = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "mask"); value.Exists() && !data.SecondaryNetworks[i].Mask.IsNull() {
			data.SecondaryNetworks[i].Mask = types.StringValue(value.String())
		} else {
			data.SecondaryNetworks[i].Mask = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "secondary"); !data.SecondaryNetworks[i].Secondary.IsNull() {
			if value.Exists() {
				data.SecondaryNetworks[i].Secondary = types.BoolValue(true)
			} else {
				data.SecondaryNetworks[i].Secondary = types.BoolValue(false)
			}
		} else {
			data.SecondaryNetworks[i].Secondary = types.BoolNull()
		}
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/host/number"); value.Exists() && !data.HostNumber.IsNull() {
		data.HostNumber = types.StringValue(value.String())
	} else {
		data.HostNumber = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/host/mask"); value.Exists() && !data.HostMask.IsNull() {
		data.HostMask = types.StringValue(value.String())
	} else {
		data.HostMask = types.StringNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/default-router/default-router-list"); value.Exists() && !data.DefaultRouters.IsNull() {
		data.DefaultRouters = helpers.GetStringListXML(value.Array())
	} else {
		data.DefaultRouters = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/dns-server/dns-server-list"); value.Exists() && !data.DnsServers.IsNull() {
		data.DnsServers = helpers.GetStringListXML(value.Array())
	} else {
		data.DnsServers = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/next-server"); value.Exists() && !data.NextServers.IsNull() {
		data.NextServers = helpers.GetStringListXML(value.Array())
	} else {
		data.NextServers = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/lease/lease-value/days"); value.Exists() && !data.LeaseDays.IsNull() {
		data.LeaseDays = types.Int64Value(value.Int())
	} else {
		data.LeaseDays = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/lease/lease-value/hours"); value.Exists() && !data.LeaseHours.IsNull() {
		data.LeaseHours = types.Int64Value(value.Int())
	} else {
		data.LeaseHours = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/lease/lease-value/minutes"); value.Exists() && !data.LeaseMinutes.IsNull() {
		data.LeaseMinutes = types.Int64Value(value.Int())
	} else {
		data.LeaseMinutes = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/lease/infinite"); !data.LeaseInfinite.IsNull() {
		if value.Exists() {
			data.LeaseInfinite = types.BoolValue(true)
		} else {
			data.LeaseInfinite = types.BoolValue(false)
		}
	} else {
		data.LeaseInfinite = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/utilization/mark/high/high-value"); value.Exists() && !data.UtilizationMarkHigh.IsNull() {
		data.UtilizationMarkHigh = types.Int64Value(value.Int())
	} else {
		data.UtilizationMarkHigh = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/utilization/mark/high/log"); !data.UtilizationMarkHighLog.IsNull() {
		if value.Exists() {
			data.UtilizationMarkHighLog = types.BoolValue(true)
		} else {
			data.UtilizationMarkHighLog = types.BoolValue(false)
		}
	} else {
		data.UtilizationMarkHighLog = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/utilization/mark/low/low-value"); value.Exists() && !data.UtilizationMarkLow.IsNull() {
		data.UtilizationMarkLow = types.Int64Value(value.Int())
	} else {
		data.UtilizationMarkLow = types.Int64Null()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/utilization/mark/low/log"); !data.UtilizationMarkLowLog.IsNull() {
		if value.Exists() {
			data.UtilizationMarkLowLog = types.BoolValue(true)
		} else {
			data.UtilizationMarkLowLog = types.BoolValue(false)
		}
	} else {
		data.UtilizationMarkLowLog = types.BoolNull()
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/subnet/prefix-length"); value.Exists() && !data.SubnetPrefixLength.IsNull() {
		data.SubnetPrefixLength = types.Int64Value(value.Int())
	} else {
		data.SubnetPrefixLength = types.Int64Null()
	}
	for i := range data.Options {
		keys := [...]string{"option-range"}
		keyValues := [...]string{strconv.FormatInt(data.Options[i].OptionCode.ValueInt64(), 10)}

		var r xmldot.Result
		helpers.GetFromXPath(res, "data"+data.getXPath()+"/option/option-range").ForEach(
			func(_ int, v xmldot.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := helpers.GetFromXPath(r, "option-range"); value.Exists() && !data.Options[i].OptionCode.IsNull() {
			data.Options[i].OptionCode = types.Int64Value(value.Int())
		} else {
			data.Options[i].OptionCode = types.Int64Null()
		}
		if value := helpers.GetFromXPath(r, "ascii-new"); value.Exists() && !data.Options[i].Ascii.IsNull() {
			data.Options[i].Ascii = types.StringValue(value.String())
		} else {
			data.Options[i].Ascii = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "hex-new/hex-line"); value.Exists() && !data.Options[i].Hex.IsNull() {
			data.Options[i].Hex = types.StringValue(value.String())
		} else {
			data.Options[i].Hex = types.StringNull()
		}
		if value := helpers.GetFromXPath(r, "ip-ordered"); value.Exists() && !data.Options[i].Ip.IsNull() {
			data.Options[i].Ip = helpers.GetStringListXML(value.Array())
		} else {
			data.Options[i].Ip = types.ListNull(types.StringType)
		}
		if value := helpers.GetFromXPath(r, "ip-new"); value.Exists() && !data.Options[i].IpLegacy.IsNull() {
			data.Options[i].IpLegacy = helpers.GetStringListXML(value.Array())
		} else {
			data.Options[i].IpLegacy = types.ListNull(types.StringType)
		}
	}
}

// End of section. //template:end updateFromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyXML

func (data *DHCPPool) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/vrf"); value.Exists() {
		data.Vrf = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/domain-name"); value.Exists() {
		data.DomainName = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/bootfile"); value.Exists() {
		data.Bootfile = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/client-name"); value.Exists() {
		data.ClientName = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/network/primary-network/number"); value.Exists() {
		data.NetworkNumber = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/network/primary-network/mask"); value.Exists() {
		data.NetworkMask = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/network/secondary-network"); value.Exists() {
		data.SecondaryNetworks = make([]DHCPPoolSecondaryNetworks, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := DHCPPoolSecondaryNetworks{}
			if cValue := helpers.GetFromXPath(v, "number"); cValue.Exists() {
				item.Number = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "mask"); cValue.Exists() {
				item.Mask = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "secondary"); cValue.Exists() {
				item.Secondary = types.BoolValue(true)
			} else {
				item.Secondary = types.BoolValue(false)
			}
			data.SecondaryNetworks = append(data.SecondaryNetworks, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/host/number"); value.Exists() {
		data.HostNumber = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/host/mask"); value.Exists() {
		data.HostMask = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/default-router/default-router-list"); value.Exists() {
		data.DefaultRouters = helpers.GetStringListXML(value.Array())
	} else {
		data.DefaultRouters = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/dns-server/dns-server-list"); value.Exists() {
		data.DnsServers = helpers.GetStringListXML(value.Array())
	} else {
		data.DnsServers = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/next-server"); value.Exists() {
		data.NextServers = helpers.GetStringListXML(value.Array())
	} else {
		data.NextServers = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/lease/lease-value/days"); value.Exists() {
		data.LeaseDays = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/lease/lease-value/hours"); value.Exists() {
		data.LeaseHours = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/lease/lease-value/minutes"); value.Exists() {
		data.LeaseMinutes = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/lease/infinite"); value.Exists() {
		data.LeaseInfinite = types.BoolValue(true)
	} else {
		data.LeaseInfinite = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/utilization/mark/high/high-value"); value.Exists() {
		data.UtilizationMarkHigh = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/utilization/mark/high/log"); value.Exists() {
		data.UtilizationMarkHighLog = types.BoolValue(true)
	} else {
		data.UtilizationMarkHighLog = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/utilization/mark/low/low-value"); value.Exists() {
		data.UtilizationMarkLow = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/utilization/mark/low/log"); value.Exists() {
		data.UtilizationMarkLowLog = types.BoolValue(true)
	} else {
		data.UtilizationMarkLowLog = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/subnet/prefix-length"); value.Exists() {
		data.SubnetPrefixLength = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/option/option-range"); value.Exists() {
		data.Options = make([]DHCPPoolOptions, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := DHCPPoolOptions{}
			if cValue := helpers.GetFromXPath(v, "option-range"); cValue.Exists() {
				item.OptionCode = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "ascii-new"); cValue.Exists() {
				item.Ascii = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "hex-new/hex-line"); cValue.Exists() {
				item.Hex = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "ip-ordered"); cValue.Exists() {
				item.Ip = helpers.GetStringListXML(cValue.Array())
			} else {
				item.Ip = types.ListNull(types.StringType)
			}
			if cValue := helpers.GetFromXPath(v, "ip-new"); cValue.Exists() {
				item.IpLegacy = helpers.GetStringListXML(cValue.Array())
			} else {
				item.IpLegacy = types.ListNull(types.StringType)
			}
			data.Options = append(data.Options, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyXML

// Section below is generated&owned by "gen/generator.go". //template:begin fromBodyDataXML

func (data *DHCPPoolData) fromBodyXML(ctx context.Context, res xmldot.Result) {
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/vrf"); value.Exists() {
		data.Vrf = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/domain-name"); value.Exists() {
		data.DomainName = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/bootfile"); value.Exists() {
		data.Bootfile = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/client-name"); value.Exists() {
		data.ClientName = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/network/primary-network/number"); value.Exists() {
		data.NetworkNumber = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/network/primary-network/mask"); value.Exists() {
		data.NetworkMask = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/network/secondary-network"); value.Exists() {
		data.SecondaryNetworks = make([]DHCPPoolSecondaryNetworksData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := DHCPPoolSecondaryNetworksData{}
			if cValue := helpers.GetFromXPath(v, "number"); cValue.Exists() {
				item.Number = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "mask"); cValue.Exists() {
				item.Mask = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "secondary"); cValue.Exists() {
				item.Secondary = types.BoolValue(true)
			} else {
				item.Secondary = types.BoolValue(false)
			}
			data.SecondaryNetworks = append(data.SecondaryNetworks, item)
			return true
		})
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/host/number"); value.Exists() {
		data.HostNumber = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/host/mask"); value.Exists() {
		data.HostMask = types.StringValue(value.String())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/default-router/default-router-list"); value.Exists() {
		data.DefaultRouters = helpers.GetStringListXML(value.Array())
	} else {
		data.DefaultRouters = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/dns-server/dns-server-list"); value.Exists() {
		data.DnsServers = helpers.GetStringListXML(value.Array())
	} else {
		data.DnsServers = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/next-server"); value.Exists() {
		data.NextServers = helpers.GetStringListXML(value.Array())
	} else {
		data.NextServers = types.ListNull(types.StringType)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/lease/lease-value/days"); value.Exists() {
		data.LeaseDays = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/lease/lease-value/hours"); value.Exists() {
		data.LeaseHours = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/lease/lease-value/minutes"); value.Exists() {
		data.LeaseMinutes = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/lease/infinite"); value.Exists() {
		data.LeaseInfinite = types.BoolValue(true)
	} else {
		data.LeaseInfinite = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/utilization/mark/high/high-value"); value.Exists() {
		data.UtilizationMarkHigh = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/utilization/mark/high/log"); value.Exists() {
		data.UtilizationMarkHighLog = types.BoolValue(true)
	} else {
		data.UtilizationMarkHighLog = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/utilization/mark/low/low-value"); value.Exists() {
		data.UtilizationMarkLow = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/utilization/mark/low/log"); value.Exists() {
		data.UtilizationMarkLowLog = types.BoolValue(true)
	} else {
		data.UtilizationMarkLowLog = types.BoolValue(false)
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/subnet/prefix-length"); value.Exists() {
		data.SubnetPrefixLength = types.Int64Value(value.Int())
	}
	if value := helpers.GetFromXPath(res, "data"+data.getXPath()+"/option/option-range"); value.Exists() {
		data.Options = make([]DHCPPoolOptionsData, 0)
		value.ForEach(func(_ int, v xmldot.Result) bool {
			item := DHCPPoolOptionsData{}
			if cValue := helpers.GetFromXPath(v, "option-range"); cValue.Exists() {
				item.OptionCode = types.Int64Value(cValue.Int())
			}
			if cValue := helpers.GetFromXPath(v, "ascii-new"); cValue.Exists() {
				item.Ascii = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "hex-new/hex-line"); cValue.Exists() {
				item.Hex = types.StringValue(cValue.String())
			}
			if cValue := helpers.GetFromXPath(v, "ip-ordered"); cValue.Exists() {
				item.Ip = helpers.GetStringListXML(cValue.Array())
			} else {
				item.Ip = types.ListNull(types.StringType)
			}
			if cValue := helpers.GetFromXPath(v, "ip-new"); cValue.Exists() {
				item.IpLegacy = helpers.GetStringListXML(cValue.Array())
			} else {
				item.IpLegacy = types.ListNull(types.StringType)
			}
			data.Options = append(data.Options, item)
			return true
		})
	}
}

// End of section. //template:end fromBodyDataXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletedItemsXML

func (data *DHCPPool) addDeletedItemsXML(ctx context.Context, state DHCPPool, body string) string {
	b := netconf.NewBody(body)
	for i := range state.Options {
		stateKeys := [...]string{"option-range"}
		stateKeyValues := [...]string{strconv.FormatInt(state.Options[i].OptionCode.ValueInt64(), 10)}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.Options[i].OptionCode.ValueInt64()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.Options {
			found = true
			if state.Options[i].OptionCode.ValueInt64() != data.Options[j].OptionCode.ValueInt64() {
				found = false
			}
			if found {
				if !state.Options[i].IpLegacy.IsNull() {
					if data.Options[j].IpLegacy.IsNull() {
						var values []string
						state.Options[i].IpLegacy.ElementsAs(ctx, &values, false)
						for _, v := range values {
							b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/option/option-range%v/ip-new[.=%v]", predicates, v))
						}
					} else {
						var dataValues, stateValues []string
						data.Options[j].IpLegacy.ElementsAs(ctx, &dataValues, false)
						state.Options[i].IpLegacy.ElementsAs(ctx, &stateValues, false)
						for _, v := range stateValues {
							found := false
							for _, vv := range dataValues {
								if v == vv {
									found = true
									break
								}
							}
							if !found {
								b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/option/option-range%v/ip-new[.=%v]", predicates, v))
							}
						}
					}
				}
				if !state.Options[i].Ip.IsNull() {
					if data.Options[j].Ip.IsNull() {
						var values []string
						state.Options[i].Ip.ElementsAs(ctx, &values, false)
						for _, v := range values {
							b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/option/option-range%v/ip-ordered[.=%v]", predicates, v))
						}
					} else {
						var dataValues, stateValues []string
						data.Options[j].Ip.ElementsAs(ctx, &dataValues, false)
						state.Options[i].Ip.ElementsAs(ctx, &stateValues, false)
						for _, v := range stateValues {
							found := false
							for _, vv := range dataValues {
								if v == vv {
									found = true
									break
								}
							}
							if !found {
								b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/option/option-range%v/ip-ordered[.=%v]", predicates, v))
							}
						}
					}
				}
				if !state.Options[i].Hex.IsNull() && data.Options[j].Hex.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/option/option-range%v/hex-new/hex-line", predicates))
				}
				if !state.Options[i].Ascii.IsNull() && data.Options[j].Ascii.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/option/option-range%v/ascii-new", predicates))
				}
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/option/option-range%v", predicates))
		}
	}
	if !state.SubnetPrefixLength.IsNull() && data.SubnetPrefixLength.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/subnet/prefix-length")
	}
	if !state.UtilizationMarkLowLog.IsNull() && data.UtilizationMarkLowLog.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/utilization/mark/low/log")
	}
	if !state.UtilizationMarkLow.IsNull() && data.UtilizationMarkLow.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/utilization/mark/low/low-value")
	}
	if !state.UtilizationMarkHighLog.IsNull() && data.UtilizationMarkHighLog.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/utilization/mark/high/log")
	}
	if !state.UtilizationMarkHigh.IsNull() && data.UtilizationMarkHigh.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/utilization/mark/high/high-value")
	}
	if !state.LeaseInfinite.IsNull() && data.LeaseInfinite.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/lease/infinite")
	}
	if !state.LeaseMinutes.IsNull() && data.LeaseMinutes.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/lease/lease-value/minutes")
	}
	if !state.LeaseHours.IsNull() && data.LeaseHours.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/lease/lease-value/hours")
	}
	if !state.LeaseDays.IsNull() && data.LeaseDays.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/lease/lease-value/days")
	}
	if !state.NextServers.IsNull() {
		if data.NextServers.IsNull() {
			var values []string
			state.NextServers.ElementsAs(ctx, &values, false)
			for _, v := range values {
				b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/next-server[.=%v]", v))
			}
		} else {
			var dataValues, stateValues []string
			data.NextServers.ElementsAs(ctx, &dataValues, false)
			state.NextServers.ElementsAs(ctx, &stateValues, false)
			for _, v := range stateValues {
				found := false
				for _, vv := range dataValues {
					if v == vv {
						found = true
						break
					}
				}
				if !found {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/next-server[.=%v]", v))
				}
			}
		}
	}
	if !state.DnsServers.IsNull() {
		if data.DnsServers.IsNull() {
			var values []string
			state.DnsServers.ElementsAs(ctx, &values, false)
			for _, v := range values {
				b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/dns-server/dns-server-list[.=%v]", v))
			}
		} else {
			var dataValues, stateValues []string
			data.DnsServers.ElementsAs(ctx, &dataValues, false)
			state.DnsServers.ElementsAs(ctx, &stateValues, false)
			for _, v := range stateValues {
				found := false
				for _, vv := range dataValues {
					if v == vv {
						found = true
						break
					}
				}
				if !found {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/dns-server/dns-server-list[.=%v]", v))
				}
			}
		}
	}
	if !state.DefaultRouters.IsNull() {
		if data.DefaultRouters.IsNull() {
			var values []string
			state.DefaultRouters.ElementsAs(ctx, &values, false)
			for _, v := range values {
				b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/default-router/default-router-list[.=%v]", v))
			}
		} else {
			var dataValues, stateValues []string
			data.DefaultRouters.ElementsAs(ctx, &dataValues, false)
			state.DefaultRouters.ElementsAs(ctx, &stateValues, false)
			for _, v := range stateValues {
				found := false
				for _, vv := range dataValues {
					if v == vv {
						found = true
						break
					}
				}
				if !found {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/default-router/default-router-list[.=%v]", v))
				}
			}
		}
	}
	if !state.HostMask.IsNull() && data.HostMask.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/host/mask")
	}
	if !state.HostNumber.IsNull() && data.HostNumber.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/host/number")
	}
	for i := range state.SecondaryNetworks {
		stateKeys := [...]string{"number"}
		stateKeyValues := [...]string{state.SecondaryNetworks[i].Number.ValueString()}
		predicates := ""
		for i := range stateKeys {
			predicates += fmt.Sprintf("[%s='%s']", stateKeys[i], stateKeyValues[i])
		}

		emptyKeys := true
		if !reflect.ValueOf(state.SecondaryNetworks[i].Number.ValueString()).IsZero() {
			emptyKeys = false
		}
		if emptyKeys {
			continue
		}

		found := false
		for j := range data.SecondaryNetworks {
			found = true
			if state.SecondaryNetworks[i].Number.ValueString() != data.SecondaryNetworks[j].Number.ValueString() {
				found = false
			}
			if found {
				if !state.SecondaryNetworks[i].Secondary.IsNull() && data.SecondaryNetworks[j].Secondary.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/network/secondary-network%v/secondary", predicates))
				}
				if !state.SecondaryNetworks[i].Mask.IsNull() && data.SecondaryNetworks[j].Mask.IsNull() {
					b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/network/secondary-network%v/mask", predicates))
				}
				break
			}
		}
		if !found {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(state.getXPath()+"/network/secondary-network%v", predicates))
		}
	}
	if !state.NetworkMask.IsNull() && data.NetworkMask.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/network/primary-network/mask")
	}
	if !state.NetworkNumber.IsNull() && data.NetworkNumber.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/network/primary-network/number")
	}
	if !state.ClientName.IsNull() && data.ClientName.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/client-name")
	}
	if !state.Bootfile.IsNull() && data.Bootfile.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/bootfile")
	}
	if !state.DomainName.IsNull() && data.DomainName.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/domain-name")
	}
	if !state.Vrf.IsNull() && data.Vrf.IsNull() {
		b = helpers.RemoveFromXPath(b, state.getXPath()+"/vrf")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletedItemsXML

// Section below is generated&owned by "gen/generator.go". //template:begin addDeletePathsXML

func (data *DHCPPool) addDeletePathsXML(ctx context.Context, body string) string {
	b := netconf.NewBody(body)
	for i := range data.Options {
		keys := [...]string{"option-range"}
		keyValues := [...]string{strconv.FormatInt(data.Options[i].OptionCode.ValueInt64(), 10)}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/option/option-range%v", predicates))
	}
	if !data.SubnetPrefixLength.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/subnet/prefix-length")
	}
	if !data.UtilizationMarkLowLog.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/utilization/mark/low/log")
	}
	if !data.UtilizationMarkLow.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/utilization/mark/low/low-value")
	}
	if !data.UtilizationMarkHighLog.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/utilization/mark/high/log")
	}
	if !data.UtilizationMarkHigh.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/utilization/mark/high/high-value")
	}
	if !data.LeaseInfinite.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/lease/infinite")
	}
	if !data.LeaseMinutes.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/lease/lease-value/minutes")
	}
	if !data.LeaseHours.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/lease/lease-value/hours")
	}
	if !data.LeaseDays.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/lease/lease-value/days")
	}
	if !data.NextServers.IsNull() {
		var values []string
		data.NextServers.ElementsAs(ctx, &values, false)
		for _, v := range values {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/next-server[.=%v]", v))
		}
	}
	if !data.DnsServers.IsNull() {
		var values []string
		data.DnsServers.ElementsAs(ctx, &values, false)
		for _, v := range values {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/dns-server/dns-server-list[.=%v]", v))
		}
	}
	if !data.DefaultRouters.IsNull() {
		var values []string
		data.DefaultRouters.ElementsAs(ctx, &values, false)
		for _, v := range values {
			b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/default-router/default-router-list[.=%v]", v))
		}
	}
	if !data.HostMask.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/host/mask")
	}
	if !data.HostNumber.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/host/number")
	}
	for i := range data.SecondaryNetworks {
		keys := [...]string{"number"}
		keyValues := [...]string{data.SecondaryNetworks[i].Number.ValueString()}
		predicates := ""
		for i := range keys {
			predicates += fmt.Sprintf("[%s='%s']", keys[i], keyValues[i])
		}

		b = helpers.RemoveFromXPath(b, fmt.Sprintf(data.getXPath()+"/network/secondary-network%v", predicates))
	}
	if !data.NetworkMask.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/network/primary-network/mask")
	}
	if !data.NetworkNumber.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/network/primary-network/number")
	}
	if !data.ClientName.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/client-name")
	}
	if !data.Bootfile.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/bootfile")
	}
	if !data.DomainName.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/domain-name")
	}
	if !data.Vrf.IsNull() {
		b = helpers.RemoveFromXPath(b, data.getXPath()+"/vrf")
	}

	b = helpers.CleanupRedundantRemoveOperations(b)
	return b.Res()
}

// End of section. //template:end addDeletePathsXML
