// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAcc

func TestAccIosxePIMIPv6(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_pim_ipv6.test", "rp_address", "2001:db8::100"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_pim_ipv6.test", "rp_address_access_list", "ipv6_acl_1"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_pim_ipv6.test", "rp_address_bidir", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_pim_ipv6.test", "vrfs.0.vrf", "VRF1"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_pim_ipv6.test", "vrfs.0.rp_address", "2001:db8::100"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_pim_ipv6.test", "vrfs.0.rp_address_access_list", "ipv6_acl_2"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_pim_ipv6.test", "vrfs.0.rp_address_bidir", "false"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIosxePIMIPv6PrerequisitesConfig + testAccIosxePIMIPv6Config_minimum(),
			},
			{
				Config: testAccIosxePIMIPv6PrerequisitesConfig + testAccIosxePIMIPv6Config_all(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
			{
				ResourceName:            "iosxe_pim_ipv6.test",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateIdFunc:       iosxePIMIPv6ImportStateIdFunc("iosxe_pim_ipv6.test"),
				ImportStateVerifyIgnore: []string{},
				Check:                   resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAcc

// Section below is generated&owned by "gen/generator.go". //template:begin importStateIdFunc

func iosxePIMIPv6ImportStateIdFunc(resourceName string) resource.ImportStateIdFunc {
	return func(s *terraform.State) (string, error) {

		return fmt.Sprintf(""), nil
	}
}

// End of section. //template:end importStateIdFunc

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
const testAccIosxePIMIPv6PrerequisitesConfig = `
resource "iosxe_yang" "PreReq0" {
	path = "/Cisco-IOS-XE-native:native/vrf/definition[name=VRF1]"
	delete = false
	attributes = {
		"name" = "VRF1"
		"address-family/ipv6" = ""
	}
}

`

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccConfigMinimal

func testAccIosxePIMIPv6Config_minimum() string {
	config := `resource "iosxe_pim_ipv6" "test" {` + "\n"
	config += `	depends_on = [iosxe_yang.PreReq0, ]` + "\n"
	config += `}` + "\n"
	return config
}

// End of section. //template:end testAccConfigMinimal

// Section below is generated&owned by "gen/generator.go". //template:begin testAccConfigAll

func testAccIosxePIMIPv6Config_all() string {
	config := `resource "iosxe_pim_ipv6" "test" {` + "\n"
	config += `	rp_address = "2001:db8::100"` + "\n"
	config += `	rp_address_access_list = "ipv6_acl_1"` + "\n"
	config += `	rp_address_bidir = false` + "\n"
	config += `	vrfs = [{` + "\n"
	config += `		vrf = "VRF1"` + "\n"
	config += `		rp_address = "2001:db8::100"` + "\n"
	config += `		rp_address_access_list = "ipv6_acl_2"` + "\n"
	config += `		rp_address_bidir = false` + "\n"
	config += `	}]` + "\n"
	config += `	depends_on = [iosxe_yang.PreReq0, ]` + "\n"
	config += `}` + "\n"
	return config
}

// End of section. //template:end testAccConfigAll
