// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccIosxeLicense(t *testing.T) {
	if os.Getenv("LICENSE") == "" {
		t.Skip("skipping test, set environment variable LICENSE")
	}
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_license.test", "boot_level_network_advantage", "true"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_license.test", "boot_level_network_advantage_addon", "dna-advantage"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_license.test", "smart_transport_type", "Off"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIosxeLicenseConfig_minimum(),
			},
			{
				Config: testAccIosxeLicenseConfig_all(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
			{
				ResourceName:            "iosxe_license.test",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateId:           "Cisco-IOS-XE-native:native/license",
				ImportStateVerifyIgnore: []string{"boot_level_network_essentials"},
				Check:                   resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

func testAccIosxeLicenseConfig_minimum() string {
	config := `resource "iosxe_license" "test" {` + "\n"
	config += `}` + "\n"
	return config
}

func testAccIosxeLicenseConfig_all() string {
	config := `resource "iosxe_license" "test" {` + "\n"
	config += `	boot_level_network_advantage = true` + "\n"
	config += `	boot_level_network_advantage_addon = "dna-advantage"` + "\n"
	config += `	smart_transport_type = "Off"` + "\n"
	config += `}` + "\n"
	return config
}
