// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

// Section below is generated&owned by "gen/generator.go". //template:begin imports
import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
)

// End of section. //template:end imports

// Section below is generated&owned by "gen/generator.go". //template:begin testAcc

func TestAccIosxeMSDP(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_msdp.test", "originator_id", "Loopback100"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_msdp.test", "peers.0.addr", "10.1.1.1"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_msdp.test", "peers.0.remote_as", "65000"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_msdp.test", "peers.0.connect_source_loopback", "100"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_msdp.test", "passwords.0.addr", "10.1.1.1"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_msdp.test", "passwords.0.encryption", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("iosxe_msdp.test", "passwords.0.password", "Cisco123"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccIosxeMSDPPrerequisitesConfig + testAccIosxeMSDPConfig_minimum(),
			},
			{
				Config: testAccIosxeMSDPPrerequisitesConfig + testAccIosxeMSDPConfig_all(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
			{
				ResourceName:            "iosxe_msdp.test",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateIdFunc:       iosxeMSDPImportStateIdFunc("iosxe_msdp.test"),
				ImportStateVerifyIgnore: []string{},
				Check:                   resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

// End of section. //template:end testAcc

// Section below is generated&owned by "gen/generator.go". //template:begin importStateIdFunc

func iosxeMSDPImportStateIdFunc(resourceName string) resource.ImportStateIdFunc {
	return func(s *terraform.State) (string, error) {

		return fmt.Sprintf(""), nil
	}
}

// End of section. //template:end importStateIdFunc

// Section below is generated&owned by "gen/generator.go". //template:begin testPrerequisites
const testAccIosxeMSDPPrerequisitesConfig = `
resource "iosxe_restconf" "PreReq0" {
	path = "Cisco-IOS-XE-native:native/interface/Loopback=100"
	attributes = {
		"name" = "100"
	}
}

`

// End of section. //template:end testPrerequisites

// Section below is generated&owned by "gen/generator.go". //template:begin testAccConfigMinimal

func testAccIosxeMSDPConfig_minimum() string {
	config := `resource "iosxe_msdp" "test" {` + "\n"
	config += `	depends_on = [iosxe_restconf.PreReq0, ]` + "\n"
	config += `}` + "\n"
	return config
}

// End of section. //template:end testAccConfigMinimal

// Section below is generated&owned by "gen/generator.go". //template:begin testAccConfigAll

func testAccIosxeMSDPConfig_all() string {
	config := `resource "iosxe_msdp" "test" {` + "\n"
	config += `	originator_id = "Loopback100"` + "\n"
	config += `	peers = [{` + "\n"
	config += `		addr = "10.1.1.1"` + "\n"
	config += `		remote_as = 65000` + "\n"
	config += `		connect_source_loopback = 100` + "\n"
	config += `	}]` + "\n"
	config += `	passwords = [{` + "\n"
	config += `		addr = "10.1.1.1"` + "\n"
	config += `		encryption = 0` + "\n"
	config += `		password = "Cisco123"` + "\n"
	config += `	}]` + "\n"
	config += `	depends_on = [iosxe_restconf.PreReq0, ]` + "\n"
	config += `}` + "\n"
	return config
}

// End of section. //template:end testAccConfigAll
